// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Agent Body",
  "slug": "agentbody",
  "operationCount": 9,
  "groups": [
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "LinkedIn Profile",
          "link": "/model-api-reference/platform-apis/agentbody/linkedin-profile"
        },
        {
          "text": "YouTube Channel Email",
          "link": "/model-api-reference/platform-apis/agentbody/youtube-channel-email"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "YouTube Transcript",
          "link": "/model-api-reference/platform-apis/agentbody/youtube-transcript"
        },
        {
          "text": "TikTok Transcript",
          "link": "/model-api-reference/platform-apis/agentbody/tiktok-transcript"
        },
        {
          "text": "TikTok Transcribe",
          "link": "/model-api-reference/platform-apis/agentbody/tiktok-transcribe"
        },
        {
          "text": "Document Parse",
          "link": "/model-api-reference/platform-apis/agentbody/document-parse"
        },
        {
          "text": "Humanize Writing",
          "link": "/model-api-reference/platform-apis/agentbody/humanize-writing"
        },
        {
          "text": "LinkedIn Email",
          "link": "/model-api-reference/platform-apis/agentbody/linkedin-email"
        },
        {
          "text": "LinkedIn Phone",
          "link": "/model-api-reference/platform-apis/agentbody/linkedin-phone"
        }
      ]
    }
  ]
} as const
