// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "AGRouter",
  "slug": "agrouter",
  "operationCount": 18,
  "groups": [
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Calendly",
          "link": "/model-api-reference/platform-apis/agrouter/calendly"
        },
        {
          "text": "Discord",
          "link": "/model-api-reference/platform-apis/agrouter/discord"
        },
        {
          "text": "GitLab",
          "link": "/model-api-reference/platform-apis/agrouter/gitlab"
        },
        {
          "text": "Gmail",
          "link": "/model-api-reference/platform-apis/agrouter/gmail"
        },
        {
          "text": "Google Calendar",
          "link": "/model-api-reference/platform-apis/agrouter/google-calendar"
        },
        {
          "text": "Google Sheets",
          "link": "/model-api-reference/platform-apis/agrouter/google-sheets"
        },
        {
          "text": "LinkedIn",
          "link": "/model-api-reference/platform-apis/agrouter/linkedin"
        },
        {
          "text": "Sentry",
          "link": "/model-api-reference/platform-apis/agrouter/sentry"
        },
        {
          "text": "Stripe",
          "link": "/model-api-reference/platform-apis/agrouter/stripe"
        },
        {
          "text": "Supabase",
          "link": "/model-api-reference/platform-apis/agrouter/supabase"
        },
        {
          "text": "Vercel",
          "link": "/model-api-reference/platform-apis/agrouter/vercel"
        },
        {
          "text": "X (Twitter)",
          "link": "/model-api-reference/platform-apis/agrouter/twitter"
        },
        {
          "text": "Airtable",
          "link": "/model-api-reference/platform-apis/agrouter/airtable"
        },
        {
          "text": "GitHub",
          "link": "/model-api-reference/platform-apis/agrouter/github"
        },
        {
          "text": "HubSpot",
          "link": "/model-api-reference/platform-apis/agrouter/hubspot"
        },
        {
          "text": "Linear",
          "link": "/model-api-reference/platform-apis/agrouter/linear"
        },
        {
          "text": "Notion",
          "link": "/model-api-reference/platform-apis/agrouter/notion"
        },
        {
          "text": "Slack",
          "link": "/model-api-reference/platform-apis/agrouter/slack"
        }
      ]
    }
  ]
} as const
