// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Bilibili",
  "slug": "bilibili",
  "operationCount": 41,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Get general search data",
          "link": "/model-api-reference/platform-apis/bilibili/web/general-search"
        },
        {
          "text": "Get home feed",
          "link": "/model-api-reference/platform-apis/bilibili/app/home-feed"
        },
        {
          "text": "Get hot search data",
          "link": "/model-api-reference/platform-apis/bilibili/web/hot-search"
        },
        {
          "text": "Get popular feed",
          "link": "/model-api-reference/platform-apis/bilibili/app/popular-feed"
        },
        {
          "text": "search all",
          "link": "/model-api-reference/platform-apis/bilibili/app/search-all"
        },
        {
          "text": "search by type",
          "link": "/model-api-reference/platform-apis/bilibili/app/search-by-type"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Get comments on the specified video",
          "link": "/model-api-reference/platform-apis/bilibili/web/video-comments"
        },
        {
          "text": "Get reply detail",
          "link": "/model-api-reference/platform-apis/bilibili/app/reply-detail"
        },
        {
          "text": "Get reply to the specified comment",
          "link": "/model-api-reference/platform-apis/bilibili/web/comment-reply"
        },
        {
          "text": "Get video comments",
          "link": "/model-api-reference/platform-apis/bilibili/app/video-comments"
        }
      ]
    },
    {
      "key": "live",
      "label": "Live",
      "operations": [
        {
          "text": "Get a list of all live areas",
          "link": "/model-api-reference/platform-apis/bilibili/web/all-live-areas"
        },
        {
          "text": "Get information of specified live room",
          "link": "/model-api-reference/platform-apis/bilibili/web/live-room-detail"
        },
        {
          "text": "Get live streamers of specified live area",
          "link": "/model-api-reference/platform-apis/bilibili/web/live-streamers"
        },
        {
          "text": "Get live video data of specified room",
          "link": "/model-api-reference/platform-apis/bilibili/web/live-videos"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Get comprehensive popular video information",
          "link": "/model-api-reference/platform-apis/bilibili/web/com-popular"
        },
        {
          "text": "Get single video data",
          "link": "/model-api-reference/platform-apis/bilibili/app/one-video"
        },
        {
          "text": "Get single video data",
          "link": "/model-api-reference/platform-apis/bilibili/web/one-video"
        },
        {
          "text": "Get single video data V2",
          "link": "/model-api-reference/platform-apis/bilibili/web/one-video-v2"
        },
        {
          "text": "Get single video data V3",
          "link": "/model-api-reference/platform-apis/bilibili/web/one-video-v3"
        },
        {
          "text": "Get single video detail",
          "link": "/model-api-reference/platform-apis/bilibili/web/video-detail"
        },
        {
          "text": "Get single video play info",
          "link": "/model-api-reference/platform-apis/bilibili/web/video-play-info"
        },
        {
          "text": "Get user homepage video data",
          "link": "/model-api-reference/platform-apis/bilibili/web/user-post-videos"
        },
        {
          "text": "Get user videos",
          "link": "/model-api-reference/platform-apis/bilibili/app/user-videos"
        },
        {
          "text": "Get Video Danmaku",
          "link": "/model-api-reference/platform-apis/bilibili/web/video-danmaku"
        },
        {
          "text": "Get Video Parts By bvid",
          "link": "/model-api-reference/platform-apis/bilibili/web/video-parts"
        },
        {
          "text": "Get video playurl",
          "link": "/model-api-reference/platform-apis/bilibili/web/video-playurl"
        },
        {
          "text": "Get video subtitle info",
          "link": "/model-api-reference/platform-apis/bilibili/web/video-subtitle"
        },
        {
          "text": "Get VIP video playurl",
          "link": "/model-api-reference/platform-apis/bilibili/web/vip-video-playurl"
        },
        {
          "text": "Gets video data from a collection folder",
          "link": "/model-api-reference/platform-apis/bilibili/web/user-collection-videos"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Extract user ID",
          "link": "/model-api-reference/platform-apis/bilibili/web/get-user-id"
        },
        {
          "text": "Get dynamic information of specified user",
          "link": "/model-api-reference/platform-apis/bilibili/web/user-dynamic"
        },
        {
          "text": "Get information of specified user",
          "link": "/model-api-reference/platform-apis/bilibili/web/user-profile"
        },
        {
          "text": "Get UP stat (total views and likes)",
          "link": "/model-api-reference/platform-apis/bilibili/web/user-up-stat"
        },
        {
          "text": "Get user collection folders",
          "link": "/model-api-reference/platform-apis/bilibili/web/collect-folders"
        },
        {
          "text": "Get user info",
          "link": "/model-api-reference/platform-apis/bilibili/app/user-info"
        },
        {
          "text": "Get user relation stat (following and followers)",
          "link": "/model-api-reference/platform-apis/bilibili/web/user-relation-stat"
        }
      ]
    },
    {
      "key": "utilities",
      "label": "Utilities",
      "operations": [
        {
          "text": "Generate aid by bvid",
          "link": "/model-api-reference/platform-apis/bilibili/web/bv-to-aid"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Get bangumi tab",
          "link": "/model-api-reference/platform-apis/bilibili/app/bangumi-tab"
        },
        {
          "text": "Get cinema tab",
          "link": "/model-api-reference/platform-apis/bilibili/app/cinema-tab"
        },
        {
          "text": "Get dynamic detail",
          "link": "/model-api-reference/platform-apis/bilibili/web/dynamic-detail"
        },
        {
          "text": "Get dynamic detail v2",
          "link": "/model-api-reference/platform-apis/bilibili/web/dynamic-detail-v2"
        }
      ]
    }
  ]
} as const
