// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Cloudsway",
  "slug": "cloudsway",
  "operationCount": 1,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Cloudsway Search",
          "link": "/model-api-reference/platform-apis/cloudsway/search"
        }
      ]
    }
  ]
} as const
