// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "DataForSEO",
  "slug": "dataforseo",
  "operationCount": 85,
  "groups": [
    {
      "key": "serp",
      "label": "SERP",
      "operations": [
        {
          "text": "SERP Baidu Organic Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/baidu/organic/live/advanced"
        },
        {
          "text": "SERP Baidu Paid Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/baidu/paid/live/advanced"
        },
        {
          "text": "SERP Bing Local Pack Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/bing/local_pack/live/advanced"
        },
        {
          "text": "SERP Bing News Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/bing/news/live/advanced"
        },
        {
          "text": "SERP Bing Organic Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/bing/organic/live/advanced"
        },
        {
          "text": "SERP Bing Paid Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/bing/paid/live/advanced"
        },
        {
          "text": "SERP Bing Shopping Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/bing/shopping/live/advanced"
        },
        {
          "text": "SERP Google Autocomplete Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/google/autocomplete/live/advanced"
        },
        {
          "text": "SERP Google Events Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/google/events/live/advanced"
        },
        {
          "text": "SERP Google Images Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/google/images/live/advanced"
        },
        {
          "text": "SERP Google Jobs Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/google/jobs/live/advanced"
        },
        {
          "text": "SERP Google Knowledge Graph Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/google/knowledge_graph/live/advanced"
        },
        {
          "text": "SERP Google Local Finder Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/google/local_finder/live/advanced"
        },
        {
          "text": "SERP Google Maps Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/google/maps/live/advanced"
        },
        {
          "text": "SERP Google News Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/google/news/live/advanced"
        },
        {
          "text": "SERP Google Organic Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/google/organic/live/advanced"
        },
        {
          "text": "SERP Google Organic Live Regular",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/google/organic/live/regular"
        },
        {
          "text": "SERP Google Paid Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/google/paid/live/advanced"
        },
        {
          "text": "SERP Google Related Searches Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/google/related_searches/live/advanced"
        },
        {
          "text": "SERP Google Shopping Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/google/shopping/live/advanced"
        },
        {
          "text": "SERP Google Videos Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/google/videos/live/advanced"
        },
        {
          "text": "SERP Naver Organic Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/naver/organic/live/advanced"
        },
        {
          "text": "SERP Yahoo Organic Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/yahoo/organic/live/advanced"
        },
        {
          "text": "SERP Yahoo Paid Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/yahoo/paid/live/advanced"
        },
        {
          "text": "SERP Yandex Organic Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/yandex/organic/live/regular"
        },
        {
          "text": "SERP Yandex Paid Live",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/serp/yandex/paid/live/regular"
        }
      ]
    },
    {
      "key": "keywords",
      "label": "Keywords",
      "operations": [
        {
          "text": "Keywords Bing for Keywords",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/keywords_data/bing/keywords_for_keywords/live"
        },
        {
          "text": "Keywords Bing for Site",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/keywords_data/bing/keywords_for_site/live"
        },
        {
          "text": "Keywords Bing Search Volume",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/keywords_data/bing/search_volume/live"
        },
        {
          "text": "Keywords Google Ads for Keywords",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/keywords_data/google_ads/keywords_for_keywords/live"
        },
        {
          "text": "Keywords Google Ads for Site",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/keywords_data/google_ads/keywords_for_site/live"
        },
        {
          "text": "Keywords Google Ads Search Volume",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/keywords_data/google_ads/search_volume/live"
        },
        {
          "text": "Keywords Google Ads Traffic",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/keywords_data/google_ads/ad_traffic_by_keywords/live"
        },
        {
          "text": "Keywords Google Trends Explore",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/keywords_data/google_trends/explore/live"
        }
      ]
    },
    {
      "key": "backlinks",
      "label": "Backlinks",
      "operations": [
        {
          "text": "Backlinks Anchors",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/backlinks/anchors/live"
        },
        {
          "text": "Backlinks Bulk Ranks",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/backlinks/bulk_ranks/live"
        },
        {
          "text": "Backlinks Competitors",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/backlinks/competitors/live"
        },
        {
          "text": "Backlinks Domain Pages",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/backlinks/domain_pages/live"
        },
        {
          "text": "Backlinks List",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/backlinks/backlinks/live"
        },
        {
          "text": "Backlinks Referring Domains",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/backlinks/referring_domains/live"
        },
        {
          "text": "Backlinks Referring Pages",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/backlinks/referring_pages/live"
        },
        {
          "text": "Backlinks Summary",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/backlinks/summary/live"
        }
      ]
    },
    {
      "key": "business-data",
      "label": "Business Data",
      "operations": [
        {
          "text": "Business Data Google Hotels",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/business_data/google/hotel_searches/live/advanced"
        },
        {
          "text": "Business Data Google My Business",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/business_data/google/my_business_info/live/advanced"
        },
        {
          "text": "Business Data Google Reviews",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/business_data/google/reviews/live/advanced"
        },
        {
          "text": "Business Data Trustpilot Reviews",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/business_data/trustpilot/reviews/live/advanced"
        },
        {
          "text": "Business Data Yelp Reviews",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/business_data/yelp/reviews/live/advanced"
        },
        {
          "text": "Business Data Yelp Search",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/business_data/yelp/search/live/advanced"
        }
      ]
    },
    {
      "key": "app-data",
      "label": "App Data",
      "operations": [
        {
          "text": "App Data Apple App Info",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/app_data/apple/app_info/live/advanced"
        },
        {
          "text": "App Data Apple App Reviews",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/app_data/apple/app_reviews/live/advanced"
        },
        {
          "text": "App Data Google App Info",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/app_data/google/app_info/live/advanced"
        },
        {
          "text": "App Data Google App Reviews",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/app_data/google/app_reviews/live/advanced"
        },
        {
          "text": "App Data Google App Searches",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/app_data/google/app_searches/live/advanced"
        }
      ]
    },
    {
      "key": "merchant",
      "label": "Merchant",
      "operations": [
        {
          "text": "Merchant Amazon Products",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/merchant/amazon/products/live/advanced"
        },
        {
          "text": "Merchant Amazon Sellers",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/merchant/amazon/sellers/live/advanced"
        },
        {
          "text": "Merchant Google Products",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/merchant/google/products/live/advanced"
        },
        {
          "text": "Merchant Google Sellers",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/merchant/google/sellers/live/advanced"
        }
      ]
    },
    {
      "key": "on-page",
      "label": "On-Page",
      "operations": [
        {
          "text": "OnPage Content Parsing",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/on_page/content_parsing/live"
        },
        {
          "text": "OnPage Duplicate Tags",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/on_page/duplicate_tags"
        },
        {
          "text": "OnPage Instant Pages",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/on_page/instant_pages"
        },
        {
          "text": "OnPage Keyword Density",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/on_page/keyword_density/live"
        },
        {
          "text": "OnPage Lighthouse",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/on_page/lighthouse/live/json"
        },
        {
          "text": "OnPage Page Screenshot",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/on_page/page_screenshot"
        },
        {
          "text": "OnPage Raw HTML",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/on_page/raw_html/live"
        }
      ]
    },
    {
      "key": "domain-analytics",
      "label": "Domain Analytics",
      "operations": [
        {
          "text": "Domain Analytics Aggregation",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/domain_analytics/technologies/aggregation_technologies/live"
        },
        {
          "text": "Domain Analytics By HTML Terms",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/domain_analytics/technologies/domains_by_html_terms/live"
        },
        {
          "text": "Domain Analytics Domains By Tech",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/domain_analytics/technologies/domains_by_technology/live"
        },
        {
          "text": "Domain Analytics Tech Stats",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/domain_analytics/technologies/technology_stats/live"
        },
        {
          "text": "Domain Analytics Technologies",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/domain_analytics/technologies/domain_technologies/live"
        },
        {
          "text": "Domain Analytics WHOIS",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/domain_analytics/whois/live"
        }
      ]
    },
    {
      "key": "content-analysis",
      "label": "Content Analysis",
      "operations": [
        {
          "text": "Content Analysis Ratings",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/content_analysis/rating_distribution/live"
        },
        {
          "text": "Content Analysis Search",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/content_analysis/search/live"
        },
        {
          "text": "Content Analysis Sentiment",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/content_analysis/sentiment_analysis/live"
        },
        {
          "text": "Content Analysis Summary",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/content_analysis/summary/live"
        }
      ]
    },
    {
      "key": "labs",
      "label": "Labs",
      "operations": [
        {
          "text": "Labs Google Bulk Keyword Difficulty",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/dataforseo_labs/google/bulk_keyword_difficulty/live"
        },
        {
          "text": "Labs Google Competitors Domain",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/dataforseo_labs/google/competitors_domain/live"
        },
        {
          "text": "Labs Google Domain Intersection",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/dataforseo_labs/google/domain_intersection/live"
        },
        {
          "text": "Labs Google Domain Rank Overview",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/dataforseo_labs/google/domain_rank_overview/live"
        },
        {
          "text": "Labs Google Historical Search Volume",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/dataforseo_labs/google/historical_search_volume/live"
        },
        {
          "text": "Labs Google Keyword Ideas",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/dataforseo_labs/google/keyword_ideas/live"
        },
        {
          "text": "Labs Google Keyword Suggestions",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/dataforseo_labs/google/keyword_suggestions/live"
        },
        {
          "text": "Labs Google Keywords for Site",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/dataforseo_labs/google/keywords_for_site/live"
        },
        {
          "text": "Labs Google Page Intersection",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/dataforseo_labs/google/page_intersection/live"
        },
        {
          "text": "Labs Google Ranked Keywords",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/dataforseo_labs/google/ranked_keywords/live"
        },
        {
          "text": "Labs Google Related Keywords",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/dataforseo_labs/google/related_keywords/live"
        },
        {
          "text": "Labs Google SERP Competitors",
          "link": "/model-api-reference/platform-apis/dataforseo/v3/dataforseo_labs/google/serp_competitors/live"
        }
      ]
    }
  ]
} as const
