// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Douyin",
  "slug": "douyin",
  "operationCount": 309,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Brand search suggest",
          "link": "/model-api-reference/platform-apis/douyin/index/brand-suggest"
        },
        {
          "text": "Content consume trend",
          "link": "/model-api-reference/platform-apis/douyin/index/content-consume-trend"
        },
        {
          "text": "Content interact trend",
          "link": "/model-api-reference/platform-apis/douyin/index/content-interact-trend"
        },
        {
          "text": "Content publish trend",
          "link": "/model-api-reference/platform-apis/douyin/index/content-publish-trend"
        },
        {
          "text": "Creative keyword related items",
          "link": "/model-api-reference/platform-apis/douyin/index/content-creative-keyword-items"
        },
        {
          "text": "Delivery analysis trend graph",
          "link": "/model-api-reference/platform-apis/douyin/douplus/analyse-graph"
        },
        {
          "text": "Fetch account search list",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-account-search-list"
        },
        {
          "text": "Fetch discussion search",
          "link": "/model-api-reference/platform-apis/douyin/search/discuss-search"
        },
        {
          "text": "Fetch experience search",
          "link": "/model-api-reference/platform-apis/douyin/search/experience-search"
        },
        {
          "text": "Fetch fan interest search term in the last 3 days 10 search terms",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-account-fans-interest-search-list"
        },
        {
          "text": "Fetch general search V1",
          "link": "/model-api-reference/platform-apis/douyin/search/general-search-v1"
        },
        {
          "text": "Fetch general search V2",
          "link": "/model-api-reference/platform-apis/douyin/search/general-search-v2"
        },
        {
          "text": "Fetch hashtag search V1",
          "link": "/model-api-reference/platform-apis/douyin/search/challenge-search-v1"
        },
        {
          "text": "Fetch hashtag search V2",
          "link": "/model-api-reference/platform-apis/douyin/search/challenge-search-v2"
        },
        {
          "text": "Fetch hashtag suggestions",
          "link": "/model-api-reference/platform-apis/douyin/search/challenge-suggest"
        },
        {
          "text": "Fetch image search",
          "link": "/model-api-reference/platform-apis/douyin/search/image-search"
        },
        {
          "text": "Fetch image-text search V3",
          "link": "/model-api-reference/platform-apis/douyin/search/image-search-v3"
        },
        {
          "text": "Fetch item search keywords statistics",
          "link": "/model-api-reference/platform-apis/douyin/creator-v2/item-search-keyword"
        },
        {
          "text": "Fetch item watch trend analysis",
          "link": "/model-api-reference/platform-apis/douyin/creator-v2/item-watch-trend"
        },
        {
          "text": "Fetch live search V1",
          "link": "/model-api-reference/platform-apis/douyin/search/live-search-v1"
        },
        {
          "text": "Fetch multi-type search",
          "link": "/model-api-reference/platform-apis/douyin/search/multi-search"
        },
        {
          "text": "Fetch music search",
          "link": "/model-api-reference/platform-apis/douyin/search/music-search"
        },
        {
          "text": "Fetch school search",
          "link": "/model-api-reference/platform-apis/douyin/search/school-search"
        },
        {
          "text": "Fetch search hot list",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-total-search-list"
        },
        {
          "text": "Fetch search keyword suggestions",
          "link": "/model-api-reference/platform-apis/douyin/search/search-suggest"
        },
        {
          "text": "Fetch search list with rising popularity",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-total-high-search-list"
        },
        {
          "text": "Fetch user search",
          "link": "/model-api-reference/platform-apis/douyin/search/user-search"
        },
        {
          "text": "Fetch user search V2",
          "link": "/model-api-reference/platform-apis/douyin/search/user-search-v2"
        },
        {
          "text": "Fetch vertical content tags",
          "link": "/model-api-reference/platform-apis/douyin/billboard/content-tag"
        },
        {
          "text": "Fetch video search V1",
          "link": "/model-api-reference/platform-apis/douyin/search/video-search-v1"
        },
        {
          "text": "Fetch video search V2",
          "link": "/model-api-reference/platform-apis/douyin/search/video-search-v2"
        },
        {
          "text": "Fetch vision search (image-based search)",
          "link": "/model-api-reference/platform-apis/douyin/search/vision-search"
        },
        {
          "text": "Generate Douyin share link, call Douyin APP, and jump to the specified keyword search result",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/open-app-to-keyword-search"
        },
        {
          "text": "Get brand trend lines",
          "link": "/model-api-reference/platform-apis/douyin/index/brand-lines"
        },
        {
          "text": "Get Content Trend Guide",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/content-trend-guide"
        },
        {
          "text": "Get details of specified hashtag",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/hashtag-detail"
        },
        {
          "text": "Get Douyin brand hot search list data",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/brand-hot-search-list"
        },
        {
          "text": "Get Douyin brand hot search list detail data",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/brand-hot-search-list-detail"
        },
        {
          "text": "Get Douyin hot search list data",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/hot-search-list"
        },
        {
          "text": "Get Douyin hot search results",
          "link": "/model-api-reference/platform-apis/douyin/web/hot-search-result"
        },
        {
          "text": "Get Douyin live hot search list data",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/live-hot-search-list"
        },
        {
          "text": "Get Douyin music hot search list data",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/music-hot-search-list"
        },
        {
          "text": "Get home feed data",
          "link": "/model-api-reference/platform-apis/douyin/web/home-feed"
        },
        {
          "text": "Get hot trend words",
          "link": "/model-api-reference/platform-apis/douyin/index/hot-trend-word"
        },
        {
          "text": "Get keyword valid date",
          "link": "/model-api-reference/platform-apis/douyin/index/keyword-valid-date"
        },
        {
          "text": "Get multi-keyword hot trend",
          "link": "/model-api-reference/platform-apis/douyin/index/multi-keyword-hot-trend"
        },
        {
          "text": "Get multi-keyword interpretation",
          "link": "/model-api-reference/platform-apis/douyin/index/multi-keyword-interpretation"
        },
        {
          "text": "Get Recommend Similar Star Authors",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/recommend-for-star-authors"
        },
        {
          "text": "Get recommended insight reports",
          "link": "/model-api-reference/platform-apis/douyin/index/insight-recommend"
        },
        {
          "text": "Get similar daren",
          "link": "/model-api-reference/platform-apis/douyin/index/daren-similar-users"
        },
        {
          "text": "Get video list of specified hashtag",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/hashtag-video-list"
        },
        {
          "text": "Search Anchor",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/search-anchor"
        },
        {
          "text": "Search Creator",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/search-creator"
        },
        {
          "text": "Search DOU+ user",
          "link": "/model-api-reference/platform-apis/douyin/douplus/search-user"
        },
        {
          "text": "Search Kol Advanced V2",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/search-kol-v2"
        },
        {
          "text": "Search Kol V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/search-kol-v1"
        },
        {
          "text": "Search live rooms (by Douyin ID or nickname)",
          "link": "/model-api-reference/platform-apis/douyin/douplus/search-live-room"
        },
        {
          "text": "Search talents by category",
          "link": "/model-api-reference/platform-apis/douyin/douplus/talents-by-category"
        },
        {
          "text": "Search Toutiao Creator",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/search-toutiao-creator"
        },
        {
          "text": "Search trend reports",
          "link": "/model-api-reference/platform-apis/douyin/index/report-search"
        },
        {
          "text": "Search user V2",
          "link": "/model-api-reference/platform-apis/douyin/douplus/search-user-v2"
        },
        {
          "text": "Search users",
          "link": "/model-api-reference/platform-apis/douyin/creator/user-search"
        },
        {
          "text": "Search videos (by title)",
          "link": "/model-api-reference/platform-apis/douyin/douplus/search-video"
        },
        {
          "text": "Topic search results",
          "link": "/model-api-reference/platform-apis/douyin/index/topic-query"
        },
        {
          "text": "Topic search suggest",
          "link": "/model-api-reference/platform-apis/douyin/index/topic-suggest"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Fetch work comment analysis word cloud weight",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-comment-word-list"
        },
        {
          "text": "Get Author Content Hot Comment Keywords V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/author-content-hot-comment-keywords-v1"
        },
        {
          "text": "Get Author Hot Comment Tokens",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-hot-comment-tokens"
        },
        {
          "text": "Get Author Hot Comment Tokens V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/author-hot-comment-tokens-v1"
        },
        {
          "text": "Get comment replies data of specified video",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/video-comment-replies"
        },
        {
          "text": "Get comment replies data of specified video",
          "link": "/model-api-reference/platform-apis/douyin/web/video-comment-replies"
        },
        {
          "text": "Get single video comments data",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/video-comments"
        },
        {
          "text": "Get single video comments data",
          "link": "/model-api-reference/platform-apis/douyin/web/video-comments"
        }
      ]
    },
    {
      "key": "live",
      "label": "Live",
      "operations": [
        {
          "text": "Douyin live room danmaku parameters",
          "link": "/model-api-reference/platform-apis/douyin/web/live-im-fetch"
        },
        {
          "text": "Douyin live room product information",
          "link": "/model-api-reference/platform-apis/douyin/web/live-room-product-result"
        },
        {
          "text": "Extract list webcast id",
          "link": "/model-api-reference/platform-apis/douyin/web/all-webcast-id"
        },
        {
          "text": "Extract webcast id",
          "link": "/model-api-reference/platform-apis/douyin/web/webcast-id"
        },
        {
          "text": "Fetch live room history list",
          "link": "/model-api-reference/platform-apis/douyin/creator-v2/live-room-history-list"
        },
        {
          "text": "Get live room gift user ranking",
          "link": "/model-api-reference/platform-apis/douyin/web/live-gift-ranking"
        },
        {
          "text": "Get live video data of specified user by sec_uid",
          "link": "/model-api-reference/platform-apis/douyin/web/user-live-videos-by-sec-uid"
        },
        {
          "text": "Get user live information by UID",
          "link": "/model-api-reference/platform-apis/douyin/web/user-live-info-by-uid"
        },
        {
          "text": "Get user live video data",
          "link": "/model-api-reference/platform-apis/douyin/web/user-live-videos"
        },
        {
          "text": "Gets the live stream data of the specified user by room_id V2",
          "link": "/model-api-reference/platform-apis/douyin/web/user-live-videos-by-room-id-v2"
        },
        {
          "text": "Webcast id to room id",
          "link": "/model-api-reference/platform-apis/douyin/web/webcast-id-2-room-id"
        }
      ]
    },
    {
      "key": "commerce",
      "label": "Commerce",
      "operations": [
        {
          "text": "Get Author Convert Videos or Products",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-convert-videos-or-products"
        }
      ]
    },
    {
      "key": "messaging",
      "label": "Messaging",
      "operations": [
        {
          "text": "Generate Douyin share link, call Douyin APP, and send private messages to specified users",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/open-app-to-send-private-message"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Anime Video",
          "link": "/model-api-reference/platform-apis/douyin/web/cartoon-aweme"
        },
        {
          "text": "Batch get the highest quality play URL of videos",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/multi-video-high-quality-play-url"
        },
        {
          "text": "Batch get the highest quality play URL of videos",
          "link": "/model-api-reference/platform-apis/douyin/web/multi-video-high-quality-play-url"
        },
        {
          "text": "Batch Get Video Information",
          "link": "/model-api-reference/platform-apis/douyin/web/multi-video"
        },
        {
          "text": "Batch Get Video Information V1",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/multi-video"
        },
        {
          "text": "Batch Get Video Information V2",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/multi-video-v2"
        },
        {
          "text": "Brand hot videos time scope",
          "link": "/model-api-reference/platform-apis/douyin/index/brand-hot-videos-time-scope"
        },
        {
          "text": "Challenge Posts",
          "link": "/model-api-reference/platform-apis/douyin/web/challenge-posts"
        },
        {
          "text": "Douyin video channel data",
          "link": "/model-api-reference/platform-apis/douyin/web/video-channel-result"
        },
        {
          "text": "Download item list",
          "link": "/model-api-reference/platform-apis/douyin/creator-v2/item-list-download"
        },
        {
          "text": "Fetch account work analysis - last week",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-account-item-analysis-list"
        },
        {
          "text": "Fetch item analysis involved vertical",
          "link": "/model-api-reference/platform-apis/douyin/creator-v2/item-analysis-involved-vertical"
        },
        {
          "text": "Fetch item analysis item performance",
          "link": "/model-api-reference/platform-apis/douyin/creator-v2/item-analysis-item-performance"
        },
        {
          "text": "Fetch item analysis overview",
          "link": "/model-api-reference/platform-apis/douyin/creator-v2/item-analysis-overview"
        },
        {
          "text": "Fetch item audience others analysis",
          "link": "/model-api-reference/platform-apis/douyin/creator-v2/item-audience-others"
        },
        {
          "text": "Fetch item audience portrait",
          "link": "/model-api-reference/platform-apis/douyin/creator-v2/item-audience-portrait"
        },
        {
          "text": "Fetch item bullet analysis",
          "link": "/model-api-reference/platform-apis/douyin/creator-v2/item-danmaku-analysis"
        },
        {
          "text": "Fetch item list",
          "link": "/model-api-reference/platform-apis/douyin/creator-v2/item-list"
        },
        {
          "text": "Fetch item overview data",
          "link": "/model-api-reference/platform-apis/douyin/creator-v2/item-overview-data"
        },
        {
          "text": "Fetch item play source statistics",
          "link": "/model-api-reference/platform-apis/douyin/creator-v2/item-play-source"
        },
        {
          "text": "Fetch post data trend",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-item-trends-list"
        },
        {
          "text": "Fetch video hot list",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-total-video-list"
        },
        {
          "text": "Food Video",
          "link": "/model-api-reference/platform-apis/douyin/web/food-aweme"
        },
        {
          "text": "Game Video",
          "link": "/model-api-reference/platform-apis/douyin/web/game-aweme"
        },
        {
          "text": "Generate Douyin share link, call Douyin APP, and jump to the specified video details page",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/open-app-to-video-detail"
        },
        {
          "text": "Generate Douyin video share QR code",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/generate-video-share-qrcode"
        },
        {
          "text": "Get Author Homepage Videos",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-homepage-videos"
        },
        {
          "text": "Get Author Show Items",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-show-items"
        },
        {
          "text": "Get creator hot music billboard",
          "link": "/model-api-reference/platform-apis/douyin/creator/creator-hot-music-billboard"
        },
        {
          "text": "Get daren core metrics",
          "link": "/model-api-reference/platform-apis/douyin/index/daren-great-item-mile-info"
        },
        {
          "text": "Get daren top videos",
          "link": "/model-api-reference/platform-apis/douyin/index/daren-great-user-top-video"
        },
        {
          "text": "Get details of specified music",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/music-detail"
        },
        {
          "text": "Get DOU+ video ranking",
          "link": "/model-api-reference/platform-apis/douyin/douplus/video-ranking"
        },
        {
          "text": "Get Douyin video mix detail data",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/video-mix-detail"
        },
        {
          "text": "Get Douyin video mix post list data",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/video-mix-post-list"
        },
        {
          "text": "Get Item Play Count",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/item-play-count"
        },
        {
          "text": "Get kol Convert Video Display V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/kol-convert-video-display-v1"
        },
        {
          "text": "Get kol Rec Videos V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/kol-rec-videos-v1"
        },
        {
          "text": "Get kol Video Performance V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/kol-video-performance-v1"
        },
        {
          "text": "Get promotable item list (with like & comment counts)",
          "link": "/model-api-reference/platform-apis/douyin/douplus/promotable-item-list"
        },
        {
          "text": "Get related posts recommendation data",
          "link": "/model-api-reference/platform-apis/douyin/web/related-posts"
        },
        {
          "text": "Get series video list",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/series-video-list"
        },
        {
          "text": "Get single video danmaku data",
          "link": "/model-api-reference/platform-apis/douyin/web/one-video-danmaku"
        },
        {
          "text": "Get single video data",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/one-video"
        },
        {
          "text": "Get single video data",
          "link": "/model-api-reference/platform-apis/douyin/web/one-video"
        },
        {
          "text": "Get single video data by sharing link",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/one-video-by-share-url"
        },
        {
          "text": "Get single video data by sharing link",
          "link": "/model-api-reference/platform-apis/douyin/web/one-video-by-share-url"
        },
        {
          "text": "Get single video data V2",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/one-video-v2"
        },
        {
          "text": "Get single video data V2",
          "link": "/model-api-reference/platform-apis/douyin/web/one-video-v2"
        },
        {
          "text": "Get single video data V3 (No copyright restrictions)",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/one-video-v3"
        },
        {
          "text": "Get the highest quality play URL of the video",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/video-high-quality-play-url"
        },
        {
          "text": "Get the highest quality play URL of the video",
          "link": "/model-api-reference/platform-apis/douyin/web/video-high-quality-play-url"
        },
        {
          "text": "Get the statistical data of the Post according to the video ID (like count, download count, play count, share count)",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/multi-video-statistics"
        },
        {
          "text": "Get the statistical data of the Post according to the video ID (like count, download count, play count, share count)",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/video-statistics"
        },
        {
          "text": "Get user collection data",
          "link": "/model-api-reference/platform-apis/douyin/web/user-collects-videos"
        },
        {
          "text": "Get user collection video data",
          "link": "/model-api-reference/platform-apis/douyin/web/user-collection-videos"
        },
        {
          "text": "Get user homepage posts",
          "link": "/model-api-reference/platform-apis/douyin/douplus/user-posts"
        },
        {
          "text": "Get user homepage video data",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/user-post-videos"
        },
        {
          "text": "Get user homepage video data",
          "link": "/model-api-reference/platform-apis/douyin/web/user-post-videos"
        },
        {
          "text": "Get user like video data",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/user-like-videos"
        },
        {
          "text": "Get user like video data",
          "link": "/model-api-reference/platform-apis/douyin/web/user-like-videos"
        },
        {
          "text": "Get user mix video data",
          "link": "/model-api-reference/platform-apis/douyin/web/user-mix-videos"
        },
        {
          "text": "Get video audience profile",
          "link": "/model-api-reference/platform-apis/douyin/index/item-user-profile"
        },
        {
          "text": "Get video comparison analysis",
          "link": "/model-api-reference/platform-apis/douyin/index/item-analysis"
        },
        {
          "text": "Get video danmaku list",
          "link": "/model-api-reference/platform-apis/douyin/creator/video-danmaku-list"
        },
        {
          "text": "Get video detail",
          "link": "/model-api-reference/platform-apis/douyin/index/item-base"
        },
        {
          "text": "Get video detail (by id or link)",
          "link": "/model-api-reference/platform-apis/douyin/douplus/video-detail"
        },
        {
          "text": "Get video index interpretation",
          "link": "/model-api-reference/platform-apis/douyin/index/item-index-interpret"
        },
        {
          "text": "Get video index trend",
          "link": "/model-api-reference/platform-apis/douyin/index/item-index"
        },
        {
          "text": "Get video list of specified music",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/music-video-list"
        },
        {
          "text": "Get video search filter options",
          "link": "/model-api-reference/platform-apis/douyin/index/item-filter-options"
        },
        {
          "text": "Increase the number of plays of the work according to the video ID",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/add-video-play-count"
        },
        {
          "text": "Knowledge Video",
          "link": "/model-api-reference/platform-apis/douyin/web/knowledge-aweme"
        },
        {
          "text": "Multi Get Item Stats",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/multi-get-item-stats"
        },
        {
          "text": "Music Video",
          "link": "/model-api-reference/platform-apis/douyin/web/music-aweme"
        },
        {
          "text": "Series Video",
          "link": "/model-api-reference/platform-apis/douyin/web/series-aweme"
        },
        {
          "text": "Video search results",
          "link": "/model-api-reference/platform-apis/douyin/index/item-query"
        },
        {
          "text": "Video search suggest",
          "link": "/model-api-reference/platform-apis/douyin/index/item-sug"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Content author portrait",
          "link": "/model-api-reference/platform-apis/douyin/index/content-author-portrait"
        },
        {
          "text": "Daren compare users",
          "link": "/model-api-reference/platform-apis/douyin/index/daren-compare-users-stable"
        },
        {
          "text": "Daren search suggest",
          "link": "/model-api-reference/platform-apis/douyin/index/daren-sug-great-user-list"
        },
        {
          "text": "Encrypt Douyin uid to user_id",
          "link": "/model-api-reference/platform-apis/douyin/index/encrypt-user-id"
        },
        {
          "text": "Encrypt user uid to sec_user_id",
          "link": "/model-api-reference/platform-apis/douyin/web/encrypt-uid-to-sec-user-id"
        },
        {
          "text": "Extract list user id",
          "link": "/model-api-reference/platform-apis/douyin/web/all-sec-user-id"
        },
        {
          "text": "Extract single user id",
          "link": "/model-api-reference/platform-apis/douyin/web/sec-user-id"
        },
        {
          "text": "Fetch account fan data trend",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-account-trends-list"
        },
        {
          "text": "Fetch author diagnosis",
          "link": "/model-api-reference/platform-apis/douyin/creator-v2/author-diagnosis"
        },
        {
          "text": "Fetch fan interest author 20 users",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-account-fans-interest-account-list"
        },
        {
          "text": "Fetch fan interest topic in the last 3 days 10 topics",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-account-fans-interest-topic-list"
        },
        {
          "text": "Fetch fan portrait",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-account-fans-portrait-list"
        },
        {
          "text": "Fetch hot account list",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-account-list"
        },
        {
          "text": "Fetch work like audience portrait - hot list only",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-user-portrait-list"
        },
        {
          "text": "Generate Douyin share link, call Douyin APP, and jump to the specified user profile",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/open-app-to-user-profile"
        },
        {
          "text": "Get Author Audience Distribution",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-audience-distribution"
        },
        {
          "text": "Get Author Base Info",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-base-info"
        },
        {
          "text": "Get Author Business Card Info",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-business-card-info"
        },
        {
          "text": "Get Author Content Hot Keywords",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-content-hot-keywords"
        },
        {
          "text": "Get Author Convert Ability",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-convert-ability"
        },
        {
          "text": "Get Author CP Info",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-cp-info"
        },
        {
          "text": "Get Author Daily Fans",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-daily-fans"
        },
        {
          "text": "Get Author Fans Distribution",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-fans-distribution"
        },
        {
          "text": "Get Author Link Info",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-link-info"
        },
        {
          "text": "Get Author Local Info",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-local-info"
        },
        {
          "text": "Get Author Market Fields",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-market-fields"
        },
        {
          "text": "Get Author Spread Info",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-spread-info"
        },
        {
          "text": "Get Author Touch Distribution",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/author-touch-distribution"
        },
        {
          "text": "Get batch user profile (up to 10)",
          "link": "/model-api-reference/platform-apis/douyin/web/batch-user-profile-v1"
        },
        {
          "text": "Get batch user profile (up to 50)",
          "link": "/model-api-reference/platform-apis/douyin/web/batch-user-profile-v2"
        },
        {
          "text": "Get creator activity detail",
          "link": "/model-api-reference/platform-apis/douyin/creator/creator-activity-detail"
        },
        {
          "text": "Get creator activity list",
          "link": "/model-api-reference/platform-apis/douyin/creator/creator-activity-list"
        },
        {
          "text": "Get creator content creation category",
          "link": "/model-api-reference/platform-apis/douyin/creator/creator-content-category"
        },
        {
          "text": "Get creator content creation course",
          "link": "/model-api-reference/platform-apis/douyin/creator/creator-content-course"
        },
        {
          "text": "Get creator hot challenge billboard",
          "link": "/model-api-reference/platform-apis/douyin/creator/creator-hot-challenge-billboard"
        },
        {
          "text": "Get creator hot course",
          "link": "/model-api-reference/platform-apis/douyin/creator/creator-hot-course"
        },
        {
          "text": "Get creator hot props billboard",
          "link": "/model-api-reference/platform-apis/douyin/creator/creator-hot-props-billboard"
        },
        {
          "text": "Get creator hot spot billboard",
          "link": "/model-api-reference/platform-apis/douyin/creator/creator-hot-spot-billboard"
        },
        {
          "text": "Get creator hot topic billboard",
          "link": "/model-api-reference/platform-apis/douyin/creator/creator-hot-topic-billboard"
        },
        {
          "text": "Get creator material center billboard",
          "link": "/model-api-reference/platform-apis/douyin/creator/creator-material-center-billboard"
        },
        {
          "text": "Get creator material center config",
          "link": "/model-api-reference/platform-apis/douyin/creator/creator-material-center-config"
        },
        {
          "text": "Get daren fans analysis",
          "link": "/model-api-reference/platform-apis/douyin/index/daren-great-user-fans-info"
        },
        {
          "text": "Get industry category config",
          "link": "/model-api-reference/platform-apis/douyin/creator/industry-category-config"
        },
        {
          "text": "Get information of specified user",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/user-profile"
        },
        {
          "text": "Get information of specified user by sec_user_id",
          "link": "/model-api-reference/platform-apis/douyin/web/user-profile"
        },
        {
          "text": "Get information of specified user by sec_user_id (gender, age, live level、brand)",
          "link": "/model-api-reference/platform-apis/douyin/web/user-profile-v4"
        },
        {
          "text": "Get information of specified user by uid",
          "link": "/model-api-reference/platform-apis/douyin/web/user-profile-v3"
        },
        {
          "text": "Get information of specified user by unique_id",
          "link": "/model-api-reference/platform-apis/douyin/web/user-profile-v2"
        },
        {
          "text": "Get kol Daily Fans V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/kol-daily-fans-v1"
        },
        {
          "text": "Get kol Fans Portrait V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/kol-fans-portrait-v1"
        },
        {
          "text": "Get mission task list",
          "link": "/model-api-reference/platform-apis/douyin/creator/mission-task-list"
        },
        {
          "text": "Get promoted accounts",
          "link": "/model-api-reference/platform-apis/douyin/douplus/promoted-accounts"
        },
        {
          "text": "Get topic or hot spot related videos",
          "link": "/model-api-reference/platform-apis/douyin/creator/creator-material-center-related"
        },
        {
          "text": "Get user collection",
          "link": "/model-api-reference/platform-apis/douyin/web/user-collects"
        },
        {
          "text": "Get user fans list",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/user-fans-list"
        },
        {
          "text": "Get user fans list",
          "link": "/model-api-reference/platform-apis/douyin/web/user-fans-list"
        },
        {
          "text": "Get user following list",
          "link": "/model-api-reference/platform-apis/douyin/web/user-following-list"
        },
        {
          "text": "Get user information by Short ID",
          "link": "/model-api-reference/platform-apis/douyin/web/user-profile-by-short-id"
        },
        {
          "text": "Get user information by UID",
          "link": "/model-api-reference/platform-apis/douyin/web/user-profile-by-uid"
        },
        {
          "text": "Get User Profile QRCode",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/user-profile-qrcode"
        },
        {
          "text": "Get user series list",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/user-series-list"
        },
        {
          "text": "Get user subscribed keywords",
          "link": "/model-api-reference/platform-apis/douyin/index/get-user-sub-word"
        },
        {
          "text": "Get Xingtu Author ID by Douyin sec_user_id",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/xingtu-kolid-by-sec-user-id"
        },
        {
          "text": "Get Xingtu Author ID by Douyin UID",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/xingtu-kolid-by-uid"
        },
        {
          "text": "Get XingTu kolid by Douyin sec_user_id",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/xingtu-kolid-by-sec-user-id"
        },
        {
          "text": "Get XingTu kolid by Douyin User ID",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/xingtu-kolid-by-uid"
        },
        {
          "text": "Multi Get Author Info",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/multi-get-author-info"
        },
        {
          "text": "Query Douyin user basic information",
          "link": "/model-api-reference/platform-apis/douyin/web/query-user"
        }
      ]
    },
    {
      "key": "utilities",
      "label": "Utilities",
      "operations": [
        {
          "text": "Douyin APP register device",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/register-device"
        },
        {
          "text": "Extract list video id",
          "link": "/model-api-reference/platform-apis/douyin/web/all-aweme-id"
        },
        {
          "text": "Extract single video id",
          "link": "/model-api-reference/platform-apis/douyin/web/aweme-id"
        },
        {
          "text": "Generate A-Bogus parameter using API URL",
          "link": "/model-api-reference/platform-apis/douyin/web/generate-a-bogus"
        },
        {
          "text": "Generate barrage xb signature",
          "link": "/model-api-reference/platform-apis/douyin/web/generate-wss-xb-signature"
        },
        {
          "text": "Generate Douyin short link",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/generate-short-url"
        },
        {
          "text": "Generate real msToken",
          "link": "/model-api-reference/platform-apis/douyin/web/generate-real-ms-token"
        },
        {
          "text": "Generate s_v_web_id",
          "link": "/model-api-reference/platform-apis/douyin/web/generate-s-v-web-id"
        },
        {
          "text": "Generate ttwid",
          "link": "/model-api-reference/platform-apis/douyin/web/generate-ttwid"
        },
        {
          "text": "Generate verify_fp",
          "link": "/model-api-reference/platform-apis/douyin/web/generate-verify-fp"
        },
        {
          "text": "Generate X-Bogus parameter using API URL",
          "link": "/model-api-reference/platform-apis/douyin/web/generate-x-bogus"
        },
        {
          "text": "Get DOU+ sec_token for POST requests",
          "link": "/model-api-reference/platform-apis/douyin/douplus/sec-token"
        },
        {
          "text": "Get the guest Cookie of Douyin Web",
          "link": "/model-api-reference/platform-apis/douyin/web/web-guest-cookie"
        },
        {
          "text": "Get Xingtu Author ID by Douyin unique_id",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/xingtu-kolid-by-unique-id"
        },
        {
          "text": "Get XingTu kolid by Douyin unique_id",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/xingtu-kolid-by-unique-id"
        },
        {
          "text": "Shorten URL",
          "link": "/model-api-reference/platform-apis/douyin/web/shorten-url"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Content consumer portrait",
          "link": "/model-api-reference/platform-apis/douyin/index/content-consumer-portrait"
        },
        {
          "text": "Content creative duration",
          "link": "/model-api-reference/platform-apis/douyin/index/content-creative-duration"
        },
        {
          "text": "Content creative keywords",
          "link": "/model-api-reference/platform-apis/douyin/index/content-creative-keywords"
        },
        {
          "text": "Content creative topic",
          "link": "/model-api-reference/platform-apis/douyin/index/content-creative-topic"
        },
        {
          "text": "Delivery analysis detail",
          "link": "/model-api-reference/platform-apis/douyin/douplus/analyse-detail"
        },
        {
          "text": "Delivery analysis overview",
          "link": "/model-api-reference/platform-apis/douyin/douplus/analyse-overview"
        },
        {
          "text": "DOU+ cost estimation",
          "link": "/model-api-reference/platform-apis/douyin/douplus/calculate-cost"
        },
        {
          "text": "Fetch activity calendar",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-calendar-list"
        },
        {
          "text": "Fetch activity calendar detail",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-calendar-detail"
        },
        {
          "text": "Fetch all hot content words",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-total-hot-word-list"
        },
        {
          "text": "Fetch Chinese city list",
          "link": "/model-api-reference/platform-apis/douyin/billboard/city-list"
        },
        {
          "text": "Fetch city hot list",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-city-list"
        },
        {
          "text": "Fetch content word details",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-total-hot-word-detail-list"
        },
        {
          "text": "Fetch high completion rate list",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-total-high-play-list"
        },
        {
          "text": "Fetch high fan rate list",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-total-high-fan-list"
        },
        {
          "text": "Fetch high like rate list",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-total-high-like-list"
        },
        {
          "text": "Fetch hot challenge list",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-challenge-list"
        },
        {
          "text": "Fetch hot list category",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-category-list"
        },
        {
          "text": "Fetch low fan explosion list",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-total-low-fan-list"
        },
        {
          "text": "Fetch rising hot list",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-rise-list"
        },
        {
          "text": "Fetch topic hot list",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-total-topic-list"
        },
        {
          "text": "Fetch topic list with rising popularity",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-total-high-topic-list"
        },
        {
          "text": "Fetch total hot list",
          "link": "/model-api-reference/platform-apis/douyin/billboard/hot-total-list"
        },
        {
          "text": "Get all area list",
          "link": "/model-api-reference/platform-apis/douyin/index/all-area"
        },
        {
          "text": "Get all valid dates",
          "link": "/model-api-reference/platform-apis/douyin/index/all-valid-date"
        },
        {
          "text": "Get brand cycles",
          "link": "/model-api-reference/platform-apis/douyin/index/brand-cycles"
        },
        {
          "text": "Get brand index",
          "link": "/model-api-reference/platform-apis/douyin/index/brand-valid-info"
        },
        {
          "text": "Get brand initiative rank weekly",
          "link": "/model-api-reference/platform-apis/douyin/index/brand-initiative-rank-weekly"
        },
        {
          "text": "Get brand radar chart",
          "link": "/model-api-reference/platform-apis/douyin/index/brand-radar-chart"
        },
        {
          "text": "Get content valid date",
          "link": "/model-api-reference/platform-apis/douyin/index/content-valid-date"
        },
        {
          "text": "Get crowd portrait",
          "link": "/model-api-reference/platform-apis/douyin/index/portrait"
        },
        {
          "text": "Get current hot topics",
          "link": "/model-api-reference/platform-apis/douyin/index/current-hot-topic"
        },
        {
          "text": "Get Demander MCN List",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/demander-mcn-list"
        },
        {
          "text": "Get Excellent Case Category List",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/excellent-case-category-list"
        },
        {
          "text": "Get hot topic detail",
          "link": "/model-api-reference/platform-apis/douyin/index/hot-detail"
        },
        {
          "text": "Get hot words",
          "link": "/model-api-reference/platform-apis/douyin/index/hot-words"
        },
        {
          "text": "Get IP Activity Detail",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/ip-activity-detail"
        },
        {
          "text": "Get IP Activity Industry List",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/ip-activity-industry-list"
        },
        {
          "text": "Get IP Activity List",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/ip-activity-list"
        },
        {
          "text": "Get kol Audience Portrait V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/kol-audience-portrait-v1"
        },
        {
          "text": "Get kol Base Info V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/kol-base-info-v1"
        },
        {
          "text": "Get kol Conversion Ability Analysis V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/kol-conversion-ability-analysis-v1"
        },
        {
          "text": "Get kol Cp Info V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/kol-cp-info-v1"
        },
        {
          "text": "Get kol Data Overview V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/kol-data-overview-v1"
        },
        {
          "text": "Get kol Link Struct V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/kol-link-struct-v1"
        },
        {
          "text": "Get kol Service Price V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/kol-service-price-v1"
        },
        {
          "text": "Get kol Touch Distribution V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/kol-touch-distribution-v1"
        },
        {
          "text": "Get kol Xingtu Index V1",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/kol-xingtu-index-v1"
        },
        {
          "text": "Get Playlet Actor Rank Catalog",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/playlet-actor-rank-catalog"
        },
        {
          "text": "Get Playlet Actor Rank List",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/playlet-actor-rank-list"
        },
        {
          "text": "Get Ranking List Catalog",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/ranking-list-catalog"
        },
        {
          "text": "Get Ranking List Data",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/ranking-list-data"
        },
        {
          "text": "Get related insight recommendations",
          "link": "/model-api-reference/platform-apis/douyin/index/insight-get-rec"
        },
        {
          "text": "Get relation word analysis",
          "link": "/model-api-reference/platform-apis/douyin/index/relation-word"
        },
        {
          "text": "Get report detail",
          "link": "/model-api-reference/platform-apis/douyin/index/report-detail"
        },
        {
          "text": "Get Resource List",
          "link": "/model-api-reference/platform-apis/douyin/xingtu-v2/resource-list"
        },
        {
          "text": "Get series detail",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/series-detail"
        },
        {
          "text": "Get share info by share code",
          "link": "/model-api-reference/platform-apis/douyin/app-v3/share-info-by-share-code"
        },
        {
          "text": "Get Sign Image",
          "link": "/model-api-reference/platform-apis/douyin/xingtu/sign-image"
        },
        {
          "text": "Get talent categories",
          "link": "/model-api-reference/platform-apis/douyin/douplus/talent-categories"
        },
        {
          "text": "Get valid date for relation",
          "link": "/model-api-reference/platform-apis/douyin/index/valid-date-for-relation"
        }
      ]
    }
  ]
} as const
