// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Exa",
  "slug": "exa",
  "operationCount": 3,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Exa Search",
          "link": "/model-api-reference/platform-apis/exa/search"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Exa Contents",
          "link": "/model-api-reference/platform-apis/exa/contents"
        },
        {
          "text": "Exa Answer",
          "link": "/model-api-reference/platform-apis/exa/answer"
        }
      ]
    }
  ]
} as const
