// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Firecrawl",
  "slug": "firecrawl",
  "operationCount": 5,
  "groups": [
    {
      "key": "crawl",
      "label": "Crawl",
      "operations": [
        {
          "text": "Firecrawl Crawl",
          "link": "/model-api-reference/platform-apis/firecrawl/crawl"
        }
      ]
    },
    {
      "key": "scrape",
      "label": "Scrape",
      "operations": [
        {
          "text": "Firecrawl Scrape",
          "link": "/model-api-reference/platform-apis/firecrawl/scrape"
        },
        {
          "text": "Firecrawl Batch Scrape",
          "link": "/model-api-reference/platform-apis/firecrawl/batch/scrape"
        }
      ]
    },
    {
      "key": "search",
      "label": "Search",
      "operations": [
        {
          "text": "Firecrawl Search",
          "link": "/model-api-reference/platform-apis/firecrawl/search"
        }
      ]
    },
    {
      "key": "map",
      "label": "Map",
      "operations": [
        {
          "text": "Firecrawl Map",
          "link": "/model-api-reference/platform-apis/firecrawl/map"
        }
      ]
    }
  ]
} as const
