// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Instagram",
  "slug": "instagram",
  "operationCount": 93,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "General search",
          "link": "/model-api-reference/platform-apis/instagram/v2/general-search"
        },
        {
          "text": "General search (with pagination)",
          "link": "/model-api-reference/platform-apis/instagram/v3/general-search"
        },
        {
          "text": "Get explore feed",
          "link": "/model-api-reference/platform-apis/instagram/v3/explore"
        },
        {
          "text": "Get explore page sections",
          "link": "/model-api-reference/platform-apis/instagram/v1/explore-sections"
        },
        {
          "text": "Get hashtag posts",
          "link": "/model-api-reference/platform-apis/instagram/v2/hashtag-posts"
        },
        {
          "text": "Get hashtag posts",
          "link": "/model-api-reference/platform-apis/instagram/v3/hashtag-posts"
        },
        {
          "text": "Get posts by hashtag",
          "link": "/model-api-reference/platform-apis/instagram/v1/hashtag-posts"
        },
        {
          "text": "Get recommended Reels feed",
          "link": "/model-api-reference/platform-apis/instagram/v3/recommended-reels"
        },
        {
          "text": "Get similar users",
          "link": "/model-api-reference/platform-apis/instagram/v2/similar-users"
        },
        {
          "text": "Get similar users",
          "link": "/model-api-reference/platform-apis/instagram/v3/similar-users"
        },
        {
          "text": "Search hashtags",
          "link": "/model-api-reference/platform-apis/instagram/v2/search-hashtags"
        },
        {
          "text": "Search hashtags",
          "link": "/model-api-reference/platform-apis/instagram/v3/search-hashtags"
        },
        {
          "text": "Search locations",
          "link": "/model-api-reference/platform-apis/instagram/v2/search-locations"
        },
        {
          "text": "Search locations by coordinates",
          "link": "/model-api-reference/platform-apis/instagram/v2/search-by-coordinates"
        },
        {
          "text": "Search locations by coordinates",
          "link": "/model-api-reference/platform-apis/instagram/v3/search-by-coordinates"
        },
        {
          "text": "Search music",
          "link": "/model-api-reference/platform-apis/instagram/v2/search-music"
        },
        {
          "text": "Search reels",
          "link": "/model-api-reference/platform-apis/instagram/v2/search-reels"
        },
        {
          "text": "Search users",
          "link": "/model-api-reference/platform-apis/instagram/v2/search-users"
        },
        {
          "text": "Search users",
          "link": "/model-api-reference/platform-apis/instagram/v3/search-users"
        },
        {
          "text": "Search users/hashtags/places",
          "link": "/model-api-reference/platform-apis/instagram/v1/search"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Bulk translate comments",
          "link": "/model-api-reference/platform-apis/instagram/v3/bulk-translate-comments"
        },
        {
          "text": "Get comment replies",
          "link": "/model-api-reference/platform-apis/instagram/v1/comment-replies"
        },
        {
          "text": "Get comment replies",
          "link": "/model-api-reference/platform-apis/instagram/v2/comment-replies"
        },
        {
          "text": "Get comment replies",
          "link": "/model-api-reference/platform-apis/instagram/v3/comment-replies"
        },
        {
          "text": "Get post comments",
          "link": "/model-api-reference/platform-apis/instagram/v2/post-comments"
        },
        {
          "text": "Get post comments",
          "link": "/model-api-reference/platform-apis/instagram/v3/post-comments"
        },
        {
          "text": "Get post comments V2",
          "link": "/model-api-reference/platform-apis/instagram/v1/post-comments-v2"
        },
        {
          "text": "Translate comment or caption",
          "link": "/model-api-reference/platform-apis/instagram/v3/translate-comment"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Convert media ID to shortcode",
          "link": "/model-api-reference/platform-apis/instagram/v1/media-id-to-shortcode"
        },
        {
          "text": "Convert media ID to shortcode",
          "link": "/model-api-reference/platform-apis/instagram/v2/media-id-to-shortcode"
        },
        {
          "text": "Convert media ID to shortcode",
          "link": "/model-api-reference/platform-apis/instagram/v3/media-id-to-shortcode"
        },
        {
          "text": "Convert shortcode to media ID",
          "link": "/model-api-reference/platform-apis/instagram/v1/shortcode-to-media-id"
        },
        {
          "text": "Convert shortcode to media ID",
          "link": "/model-api-reference/platform-apis/instagram/v2/shortcode-to-media-id"
        },
        {
          "text": "Convert shortcode to media ID",
          "link": "/model-api-reference/platform-apis/instagram/v3/shortcode-to-media-id"
        },
        {
          "text": "Get location posts",
          "link": "/model-api-reference/platform-apis/instagram/v2/location-posts"
        },
        {
          "text": "Get location posts",
          "link": "/model-api-reference/platform-apis/instagram/v3/location-posts"
        },
        {
          "text": "Get music (audio) posts",
          "link": "/model-api-reference/platform-apis/instagram/v3/music-posts"
        },
        {
          "text": "Get music posts",
          "link": "/model-api-reference/platform-apis/instagram/v2/music-posts"
        },
        {
          "text": "Get post by ID",
          "link": "/model-api-reference/platform-apis/instagram/v1/post-by-id"
        },
        {
          "text": "Get post by URL",
          "link": "/model-api-reference/platform-apis/instagram/v1/post-by-url"
        },
        {
          "text": "Get post by URL V2",
          "link": "/model-api-reference/platform-apis/instagram/v1/post-by-url-v2"
        },
        {
          "text": "Get post info",
          "link": "/model-api-reference/platform-apis/instagram/v2/post-info"
        },
        {
          "text": "Get post info (media_id or URL)",
          "link": "/model-api-reference/platform-apis/instagram/v3/post-info"
        },
        {
          "text": "Get post info by shortcode",
          "link": "/model-api-reference/platform-apis/instagram/v3/post-info-by-code"
        },
        {
          "text": "Get post likes",
          "link": "/model-api-reference/platform-apis/instagram/v2/post-likes"
        },
        {
          "text": "Get post likes",
          "link": "/model-api-reference/platform-apis/instagram/v3/post-likes"
        },
        {
          "text": "Get post oEmbed info",
          "link": "/model-api-reference/platform-apis/instagram/v3/post-oembed"
        },
        {
          "text": "Get posts by location",
          "link": "/model-api-reference/platform-apis/instagram/v1/location-posts"
        },
        {
          "text": "Get posts by section",
          "link": "/model-api-reference/platform-apis/instagram/v1/section-posts"
        },
        {
          "text": "Get posts using specific music",
          "link": "/model-api-reference/platform-apis/instagram/v1/music-posts"
        },
        {
          "text": "Get user posts",
          "link": "/model-api-reference/platform-apis/instagram/v2/user-posts"
        },
        {
          "text": "Get user posts",
          "link": "/model-api-reference/platform-apis/instagram/v3/user-posts"
        },
        {
          "text": "Get user posts list",
          "link": "/model-api-reference/platform-apis/instagram/v1/user-posts"
        },
        {
          "text": "Get user posts list V2",
          "link": "/model-api-reference/platform-apis/instagram/v1/user-posts-v2"
        },
        {
          "text": "Get user tagged posts",
          "link": "/model-api-reference/platform-apis/instagram/v1/user-tagged-posts"
        },
        {
          "text": "Get user tagged posts",
          "link": "/model-api-reference/platform-apis/instagram/v2/user-tagged-posts"
        },
        {
          "text": "Get user tagged posts",
          "link": "/model-api-reference/platform-apis/instagram/v3/user-tagged-posts"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Get user about info",
          "link": "/model-api-reference/platform-apis/instagram/v1/user-about-info"
        },
        {
          "text": "Get user about info",
          "link": "/model-api-reference/platform-apis/instagram/v3/user-about"
        },
        {
          "text": "Get user brief info",
          "link": "/model-api-reference/platform-apis/instagram/v3/user-brief"
        },
        {
          "text": "Get user data by user ID",
          "link": "/model-api-reference/platform-apis/instagram/v1/user-info-by-id"
        },
        {
          "text": "Get user data by user ID V2",
          "link": "/model-api-reference/platform-apis/instagram/v1/user-info-by-id-v2"
        },
        {
          "text": "Get user data by username",
          "link": "/model-api-reference/platform-apis/instagram/v1/user-info-by-username"
        },
        {
          "text": "Get user data by username V2",
          "link": "/model-api-reference/platform-apis/instagram/v1/user-info-by-username-v2"
        },
        {
          "text": "Get user data by username V3",
          "link": "/model-api-reference/platform-apis/instagram/v1/user-info-by-username-v3"
        },
        {
          "text": "Get user followers",
          "link": "/model-api-reference/platform-apis/instagram/v2/user-followers"
        },
        {
          "text": "Get user followers list",
          "link": "/model-api-reference/platform-apis/instagram/v3/user-followers"
        },
        {
          "text": "Get user following",
          "link": "/model-api-reference/platform-apis/instagram/v2/user-following"
        },
        {
          "text": "Get user following list",
          "link": "/model-api-reference/platform-apis/instagram/v3/user-following"
        },
        {
          "text": "Get user former usernames",
          "link": "/model-api-reference/platform-apis/instagram/v3/user-former-usernames"
        },
        {
          "text": "Get user highlights",
          "link": "/model-api-reference/platform-apis/instagram/v2/user-highlights"
        },
        {
          "text": "Get user highlights",
          "link": "/model-api-reference/platform-apis/instagram/v3/user-highlights"
        },
        {
          "text": "Get user ID by username",
          "link": "/model-api-reference/platform-apis/instagram/v3/user-id-by-username"
        },
        {
          "text": "Get user info",
          "link": "/model-api-reference/platform-apis/instagram/v2/user-info"
        },
        {
          "text": "Get user info by user ID",
          "link": "/model-api-reference/platform-apis/instagram/v1/user-id-to-username"
        },
        {
          "text": "Get user info by user ID",
          "link": "/model-api-reference/platform-apis/instagram/v2/user-id-to-username"
        },
        {
          "text": "Get user info by user ID",
          "link": "/model-api-reference/platform-apis/instagram/v3/user-id-to-username"
        },
        {
          "text": "Get user profile",
          "link": "/model-api-reference/platform-apis/instagram/v3/user-profile"
        },
        {
          "text": "Get user reels",
          "link": "/model-api-reference/platform-apis/instagram/v2/user-reels"
        },
        {
          "text": "Get user reels",
          "link": "/model-api-reference/platform-apis/instagram/v3/user-reels"
        },
        {
          "text": "Get user Reels list",
          "link": "/model-api-reference/platform-apis/instagram/v1/user-reels"
        },
        {
          "text": "Get user reposts list",
          "link": "/model-api-reference/platform-apis/instagram/v1/user-reposts"
        },
        {
          "text": "Get user stories",
          "link": "/model-api-reference/platform-apis/instagram/v2/user-stories"
        },
        {
          "text": "Get user stories",
          "link": "/model-api-reference/platform-apis/instagram/v3/user-stories"
        }
      ]
    },
    {
      "key": "utilities",
      "label": "Utilities",
      "operations": [
        {
          "text": "Extract shortcode from URL",
          "link": "/model-api-reference/platform-apis/instagram/v3/extract-shortcode"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Get cities by country",
          "link": "/model-api-reference/platform-apis/instagram/v1/cities"
        },
        {
          "text": "Get highlight stories",
          "link": "/model-api-reference/platform-apis/instagram/v2/highlight-stories"
        },
        {
          "text": "Get highlight stories",
          "link": "/model-api-reference/platform-apis/instagram/v3/highlight-stories"
        },
        {
          "text": "Get location info",
          "link": "/model-api-reference/platform-apis/instagram/v1/location-info"
        },
        {
          "text": "Get location info",
          "link": "/model-api-reference/platform-apis/instagram/v3/location-info"
        },
        {
          "text": "Get locations by city",
          "link": "/model-api-reference/platform-apis/instagram/v1/locations"
        },
        {
          "text": "Get nearby location content",
          "link": "/model-api-reference/platform-apis/instagram/v3/location-nearby"
        },
        {
          "text": "Get related profiles",
          "link": "/model-api-reference/platform-apis/instagram/v1/related-profiles"
        }
      ]
    }
  ]
} as const
