// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Kuaishou",
  "slug": "kuaishou",
  "operationCount": 38,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Comprehensive search",
          "link": "/model-api-reference/platform-apis/kuaishou/app/search-comprehensive"
        },
        {
          "text": "Kuaishou hot search person board",
          "link": "/model-api-reference/platform-apis/kuaishou/app/hot-search-person"
        },
        {
          "text": "Search image",
          "link": "/model-api-reference/platform-apis/kuaishou/app/search-image"
        },
        {
          "text": "Search live",
          "link": "/model-api-reference/platform-apis/kuaishou/app/search-live"
        },
        {
          "text": "Search music",
          "link": "/model-api-reference/platform-apis/kuaishou/app/search-music"
        },
        {
          "text": "Search tag",
          "link": "/model-api-reference/platform-apis/kuaishou/app/search-tag"
        },
        {
          "text": "Search user V2",
          "link": "/model-api-reference/platform-apis/kuaishou/app/search-user-v2"
        },
        {
          "text": "Search video V2",
          "link": "/model-api-reference/platform-apis/kuaishou/app/search-video-v2"
        },
        {
          "text": "Selection feed",
          "link": "/model-api-reference/platform-apis/kuaishou/app/selection-feed"
        },
        {
          "text": "Tag feed",
          "link": "/model-api-reference/platform-apis/kuaishou/app/tag-feed"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Fetch video comments",
          "link": "/model-api-reference/platform-apis/kuaishou/web/one-video-comment"
        },
        {
          "text": "Fetch video sub comments",
          "link": "/model-api-reference/platform-apis/kuaishou/web/one-video-sub-comment"
        },
        {
          "text": "Get single video comment data",
          "link": "/model-api-reference/platform-apis/kuaishou/app/video-comment"
        },
        {
          "text": "Video sub comments",
          "link": "/model-api-reference/platform-apis/kuaishou/app/video-sub-comments"
        }
      ]
    },
    {
      "key": "live",
      "label": "Live",
      "operations": [
        {
          "text": "Fetch user live replay",
          "link": "/model-api-reference/platform-apis/kuaishou/web/user-live-replay"
        },
        {
          "text": "Get user live info",
          "link": "/model-api-reference/platform-apis/kuaishou/app/user-live-info"
        },
        {
          "text": "Kuaishou live top list",
          "link": "/model-api-reference/platform-apis/kuaishou/app/live-top-list"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Fetch single video by URL",
          "link": "/model-api-reference/platform-apis/kuaishou/app/one-video-by-url"
        },
        {
          "text": "Fetch single video by URL",
          "link": "/model-api-reference/platform-apis/kuaishou/web/one-video-by-url"
        },
        {
          "text": "Get single video data V1",
          "link": "/model-api-reference/platform-apis/kuaishou/web/one-video"
        },
        {
          "text": "Get single video data V2",
          "link": "/model-api-reference/platform-apis/kuaishou/web/one-video-v2"
        },
        {
          "text": "Get user hot post data",
          "link": "/model-api-reference/platform-apis/kuaishou/app/user-hot-post"
        },
        {
          "text": "Kuaishou batch video query API",
          "link": "/model-api-reference/platform-apis/kuaishou/app/videos-batch"
        },
        {
          "text": "Music ranking",
          "link": "/model-api-reference/platform-apis/kuaishou/app/music-ranking"
        },
        {
          "text": "User video list V2",
          "link": "/model-api-reference/platform-apis/kuaishou/app/user-post-v2"
        },
        {
          "text": "Video detailsV1",
          "link": "/model-api-reference/platform-apis/kuaishou/app/one-video"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Fetch user collect",
          "link": "/model-api-reference/platform-apis/kuaishou/web/user-collect"
        },
        {
          "text": "Fetch user ID",
          "link": "/model-api-reference/platform-apis/kuaishou/web/get-user-id"
        },
        {
          "text": "Fetch user info",
          "link": "/model-api-reference/platform-apis/kuaishou/web/user-info"
        },
        {
          "text": "Get single user data V2",
          "link": "/model-api-reference/platform-apis/kuaishou/app/one-user-v2"
        }
      ]
    },
    {
      "key": "utilities",
      "label": "Utilities",
      "operations": [
        {
          "text": "Generate Kuaishou share link",
          "link": "/model-api-reference/platform-apis/kuaishou/app/generate-share-link"
        },
        {
          "text": "Generate share short URL",
          "link": "/model-api-reference/platform-apis/kuaishou/web/generate-share-short-url"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Fetch Kuaishou Hot List V1",
          "link": "/model-api-reference/platform-apis/kuaishou/web/hot-list-v1"
        },
        {
          "text": "Fetch Kuaishou Hot List V2",
          "link": "/model-api-reference/platform-apis/kuaishou/web/hot-list-v2"
        },
        {
          "text": "Kuaishou brand top list",
          "link": "/model-api-reference/platform-apis/kuaishou/app/brand-top-list"
        },
        {
          "text": "Kuaishou hot board detail",
          "link": "/model-api-reference/platform-apis/kuaishou/app/hot-board-detail"
        },
        {
          "text": "Kuaishou hot categories",
          "link": "/model-api-reference/platform-apis/kuaishou/app/hot-board-categories"
        },
        {
          "text": "Kuaishou shopping top list",
          "link": "/model-api-reference/platform-apis/kuaishou/app/shopping-top-list"
        }
      ]
    }
  ]
} as const
