// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Lemon8",
  "slug": "lemon8",
  "operationCount": 16,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Get banners of discover page",
          "link": "/model-api-reference/platform-apis/lemon8/app/discover-banners"
        },
        {
          "text": "Get Editor's Picks of discover page",
          "link": "/model-api-reference/platform-apis/lemon8/app/discover-tab-information-tabs"
        },
        {
          "text": "Get hot search keywords",
          "link": "/model-api-reference/platform-apis/lemon8/app/hot-search-keywords"
        },
        {
          "text": "Get main content of discover page",
          "link": "/model-api-reference/platform-apis/lemon8/app/discover-tab"
        },
        {
          "text": "Search API",
          "link": "/model-api-reference/platform-apis/lemon8/app/search"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Get comments list of specified post",
          "link": "/model-api-reference/platform-apis/lemon8/app/post-comment-list"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Get information of specified post",
          "link": "/model-api-reference/platform-apis/lemon8/app/post-detail"
        },
        {
          "text": "Get post ID through sharing link",
          "link": "/model-api-reference/platform-apis/lemon8/app/item-id"
        },
        {
          "text": "Get post IDs in batch through sharing links",
          "link": "/model-api-reference/platform-apis/lemon8/app/item-ids"
        },
        {
          "text": "Get topic post list",
          "link": "/model-api-reference/platform-apis/lemon8/app/topic-post-list"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Get fans list of specified user",
          "link": "/model-api-reference/platform-apis/lemon8/app/user-follower-list"
        },
        {
          "text": "Get following list of specified user",
          "link": "/model-api-reference/platform-apis/lemon8/app/user-following-list"
        },
        {
          "text": "Get information of specified user",
          "link": "/model-api-reference/platform-apis/lemon8/app/user-profile"
        },
        {
          "text": "Get user ID through sharing link",
          "link": "/model-api-reference/platform-apis/lemon8/app/user-id"
        },
        {
          "text": "Get user IDs in batch through sharing links",
          "link": "/model-api-reference/platform-apis/lemon8/app/user-ids"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Get topic information",
          "link": "/model-api-reference/platform-apis/lemon8/app/topic-info"
        }
      ]
    }
  ]
} as const
