// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "LinkedIn",
  "slug": "linkedin",
  "operationCount": 7,
  "groups": [
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Get post comments",
          "link": "/model-api-reference/platform-apis/linkedin/web-v2/post-comments"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Get company's posts",
          "link": "/model-api-reference/platform-apis/linkedin/web-v2/company-posts"
        },
        {
          "text": "Get post or article detail",
          "link": "/model-api-reference/platform-apis/linkedin/web-v2/post-detail"
        },
        {
          "text": "Get user's posts",
          "link": "/model-api-reference/platform-apis/linkedin/web-v2/user-posts"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Get company profile",
          "link": "/model-api-reference/platform-apis/linkedin/web-v2/company-profile"
        },
        {
          "text": "Get user profile",
          "link": "/model-api-reference/platform-apis/linkedin/web-v2/user-profile"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Get job detail",
          "link": "/model-api-reference/platform-apis/linkedin/web-v2/job-detail"
        }
      ]
    }
  ]
} as const
