// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Pinterest",
  "slug": "pinterest",
  "operationCount": 4,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Pinterest Search",
          "link": "/model-api-reference/platform-apis/pinterest/search"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Pinterest User Boards",
          "link": "/model-api-reference/platform-apis/pinterest/user-boards"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Pinterest Pin Details",
          "link": "/model-api-reference/platform-apis/pinterest/pin"
        },
        {
          "text": "Pinterest Board",
          "link": "/model-api-reference/platform-apis/pinterest/board"
        }
      ]
    }
  ]
} as const
