// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Pipixia",
  "slug": "pipixia",
  "operationCount": 17,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Get hashtag detail",
          "link": "/model-api-reference/platform-apis/pipixia/app/hashtag-detail"
        },
        {
          "text": "Get hashtag post list",
          "link": "/model-api-reference/platform-apis/pipixia/app/hashtag-post-list"
        },
        {
          "text": "Get home feed",
          "link": "/model-api-reference/platform-apis/pipixia/app/home-feed"
        },
        {
          "text": "Get home short drama feed",
          "link": "/model-api-reference/platform-apis/pipixia/app/home-short-drama-feed"
        },
        {
          "text": "Get hot search board detail",
          "link": "/model-api-reference/platform-apis/pipixia/app/hot-search-board-detail"
        },
        {
          "text": "Get hot search board list",
          "link": "/model-api-reference/platform-apis/pipixia/app/hot-search-board-list"
        },
        {
          "text": "Get hot search words",
          "link": "/model-api-reference/platform-apis/pipixia/app/hot-search-words"
        },
        {
          "text": "Search API",
          "link": "/model-api-reference/platform-apis/pipixia/app/search"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Get post comment list",
          "link": "/model-api-reference/platform-apis/pipixia/app/post-comment-list"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Get post statistics",
          "link": "/model-api-reference/platform-apis/pipixia/app/post-statistics"
        },
        {
          "text": "Get single video data",
          "link": "/model-api-reference/platform-apis/pipixia/app/post-detail"
        },
        {
          "text": "Get user post list",
          "link": "/model-api-reference/platform-apis/pipixia/app/user-post-list"
        },
        {
          "text": "Increase post view count",
          "link": "/model-api-reference/platform-apis/pipixia/app/increase-post-view-count"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Get user follower list",
          "link": "/model-api-reference/platform-apis/pipixia/app/user-follower-list"
        },
        {
          "text": "Get user following list",
          "link": "/model-api-reference/platform-apis/pipixia/app/user-following-list"
        },
        {
          "text": "Get user information",
          "link": "/model-api-reference/platform-apis/pipixia/app/user-info"
        }
      ]
    },
    {
      "key": "utilities",
      "label": "Utilities",
      "operations": [
        {
          "text": "Generate short URL",
          "link": "/model-api-reference/platform-apis/pipixia/app/short-url"
        }
      ]
    }
  ]
} as const
