// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Reddit",
  "slug": "reddit",
  "operationCount": 27,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Fetch Reddit APP Dynamic Search Results",
          "link": "/model-api-reference/platform-apis/reddit/app/dynamic-search"
        },
        {
          "text": "Fetch Reddit APP Games Feed",
          "link": "/model-api-reference/platform-apis/reddit/app/games-feed"
        },
        {
          "text": "Fetch Reddit APP Home Feed",
          "link": "/model-api-reference/platform-apis/reddit/app/home-feed"
        },
        {
          "text": "Fetch Reddit APP News Feed",
          "link": "/model-api-reference/platform-apis/reddit/app/news-feed"
        },
        {
          "text": "Fetch Reddit APP Popular Feed",
          "link": "/model-api-reference/platform-apis/reddit/app/popular-feed"
        },
        {
          "text": "Fetch Reddit APP Search Typeahead Suggestions",
          "link": "/model-api-reference/platform-apis/reddit/app/search-typeahead"
        },
        {
          "text": "Fetch Reddit APP Subreddit Feed",
          "link": "/model-api-reference/platform-apis/reddit/app/subreddit-feed"
        },
        {
          "text": "Fetch Reddit APP Topic Feed",
          "link": "/model-api-reference/platform-apis/reddit/app/topic-feed"
        },
        {
          "text": "Fetch Reddit APP Trending Searches",
          "link": "/model-api-reference/platform-apis/reddit/app/trending-searches"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Fetch Reddit Answers Generated Comments",
          "link": "/model-api-reference/platform-apis/reddit/app/generated-comments"
        },
        {
          "text": "Fetch Reddit APP Comment Replies (Sub-comments)",
          "link": "/model-api-reference/platform-apis/reddit/app/comment-replies"
        },
        {
          "text": "Fetch Reddit APP Community Highlights",
          "link": "/model-api-reference/platform-apis/reddit/app/community-highlights"
        },
        {
          "text": "Fetch Reddit APP Post Comments",
          "link": "/model-api-reference/platform-apis/reddit/app/post-comments"
        },
        {
          "text": "Fetch User Comments",
          "link": "/model-api-reference/platform-apis/reddit/app/user-comments"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Fetch Reddit Answers Generated Posts",
          "link": "/model-api-reference/platform-apis/reddit/app/generated-posts"
        },
        {
          "text": "Fetch Reddit APP Subreddit Post Channels",
          "link": "/model-api-reference/platform-apis/reddit/app/subreddit-post-channels"
        },
        {
          "text": "Fetch Reddit Post Details in Batch (Max 5)",
          "link": "/model-api-reference/platform-apis/reddit/app/post-details-batch"
        },
        {
          "text": "Fetch Reddit Post Details in Large Batch (Max 30)",
          "link": "/model-api-reference/platform-apis/reddit/app/post-details-batch-large"
        },
        {
          "text": "Fetch Single Reddit Post Details",
          "link": "/model-api-reference/platform-apis/reddit/app/post-details"
        },
        {
          "text": "Fetch User Posts",
          "link": "/model-api-reference/platform-apis/reddit/app/user-posts"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Fetch Reddit APP User Profile",
          "link": "/model-api-reference/platform-apis/reddit/app/user-profile"
        },
        {
          "text": "Fetch User Public Trophies",
          "link": "/model-api-reference/platform-apis/reddit/app/user-trophies"
        },
        {
          "text": "Fetch User's Active Subreddits",
          "link": "/model-api-reference/platform-apis/reddit/app/user-active-subreddits"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Check if Subreddit is Muted",
          "link": "/model-api-reference/platform-apis/reddit/app/check-subreddit-muted"
        },
        {
          "text": "Fetch Reddit APP Subreddit Info",
          "link": "/model-api-reference/platform-apis/reddit/app/subreddit-info"
        },
        {
          "text": "Fetch Reddit APP Subreddit Rules and Style Info",
          "link": "/model-api-reference/platform-apis/reddit/app/subreddit-style"
        },
        {
          "text": "Fetch Reddit APP Subreddit Settings",
          "link": "/model-api-reference/platform-apis/reddit/app/subreddit-settings"
        }
      ]
    }
  ]
} as const
