// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "SandBase",
  "slug": "sandbase",
  "operationCount": 18,
  "groups": [
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Calendly",
          "link": "/model-api-reference/platform-apis/sandbase/calendly"
        },
        {
          "text": "Discord",
          "link": "/model-api-reference/platform-apis/sandbase/discord"
        },
        {
          "text": "GitLab",
          "link": "/model-api-reference/platform-apis/sandbase/gitlab"
        },
        {
          "text": "Gmail",
          "link": "/model-api-reference/platform-apis/sandbase/gmail"
        },
        {
          "text": "Google Calendar",
          "link": "/model-api-reference/platform-apis/sandbase/google-calendar"
        },
        {
          "text": "Google Sheets",
          "link": "/model-api-reference/platform-apis/sandbase/google-sheets"
        },
        {
          "text": "LinkedIn",
          "link": "/model-api-reference/platform-apis/sandbase/linkedin"
        },
        {
          "text": "Sentry",
          "link": "/model-api-reference/platform-apis/sandbase/sentry"
        },
        {
          "text": "Stripe",
          "link": "/model-api-reference/platform-apis/sandbase/stripe"
        },
        {
          "text": "Supabase",
          "link": "/model-api-reference/platform-apis/sandbase/supabase"
        },
        {
          "text": "Vercel",
          "link": "/model-api-reference/platform-apis/sandbase/vercel"
        },
        {
          "text": "X (Twitter)",
          "link": "/model-api-reference/platform-apis/sandbase/twitter"
        },
        {
          "text": "Airtable",
          "link": "/model-api-reference/platform-apis/sandbase/airtable"
        },
        {
          "text": "GitHub",
          "link": "/model-api-reference/platform-apis/sandbase/github"
        },
        {
          "text": "HubSpot",
          "link": "/model-api-reference/platform-apis/sandbase/hubspot"
        },
        {
          "text": "Linear",
          "link": "/model-api-reference/platform-apis/sandbase/linear"
        },
        {
          "text": "Notion",
          "link": "/model-api-reference/platform-apis/sandbase/notion"
        },
        {
          "text": "Slack",
          "link": "/model-api-reference/platform-apis/sandbase/slack"
        }
      ]
    }
  ]
} as const
