// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Scholar",
  "slug": "scholar",
  "operationCount": 4,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Scholar Smart Search",
          "link": "/model-api-reference/platform-apis/scholar/search-mixed"
        },
        {
          "text": "Scholar Web Search",
          "link": "/model-api-reference/platform-apis/scholar/search-web"
        },
        {
          "text": "Scholar Academic Search",
          "link": "/model-api-reference/platform-apis/scholar/search-scholar"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Scholar Explain",
          "link": "/model-api-reference/platform-apis/scholar/explain"
        }
      ]
    }
  ]
} as const
