// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Tavily",
  "slug": "tavily",
  "operationCount": 3,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Tavily Search",
          "link": "/model-api-reference/platform-apis/tavily/search"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Tavily Extract",
          "link": "/model-api-reference/platform-apis/tavily/extract"
        },
        {
          "text": "Tavily Map",
          "link": "/model-api-reference/platform-apis/tavily/map"
        }
      ]
    }
  ]
} as const
