// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Telegram",
  "slug": "telegram",
  "operationCount": 7,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Search posts in a channel",
          "link": "/model-api-reference/platform-apis/telegram/web/channel-search"
        },
        {
          "text": "Similar channels",
          "link": "/model-api-reference/platform-apis/telegram/web/similar-channels"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Post comments",
          "link": "/model-api-reference/platform-apis/telegram/web/post-comments"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Get channel posts (paginated)",
          "link": "/model-api-reference/platform-apis/telegram/web/channel-posts"
        },
        {
          "text": "Get single post",
          "link": "/model-api-reference/platform-apis/telegram/web/post-detail"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Batch channel info",
          "link": "/model-api-reference/platform-apis/telegram/web/batch-channel-info"
        },
        {
          "text": "Get channel info",
          "link": "/model-api-reference/platform-apis/telegram/web/channel-info"
        }
      ]
    }
  ]
} as const
