// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Temp Mail",
  "slug": "temp-mail",
  "operationCount": 3,
  "groups": [
    {
      "key": "messaging",
      "label": "Messaging",
      "operations": [
        {
          "text": "Get Emails",
          "link": "/model-api-reference/platform-apis/temp-mail/v1/emails-inbox"
        }
      ]
    },
    {
      "key": "utilities",
      "label": "Utilities",
      "operations": [
        {
          "text": "Get Email By Id",
          "link": "/model-api-reference/platform-apis/temp-mail/v1/email-by-id"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Get Temp Email",
          "link": "/model-api-reference/platform-apis/temp-mail/v1/temp-email-address"
        }
      ]
    }
  ]
} as const
