// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Threads",
  "slug": "threads",
  "operationCount": 11,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Search profiles",
          "link": "/model-api-reference/platform-apis/threads/web/search-profiles"
        },
        {
          "text": "Search recent content",
          "link": "/model-api-reference/platform-apis/threads/web/search-recent"
        },
        {
          "text": "Search top content",
          "link": "/model-api-reference/platform-apis/threads/web/search-top"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Get post comments",
          "link": "/model-api-reference/platform-apis/threads/web/post-comments"
        },
        {
          "text": "Get user replies",
          "link": "/model-api-reference/platform-apis/threads/web/user-replies"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Get post detail",
          "link": "/model-api-reference/platform-apis/threads/web/post-detail"
        },
        {
          "text": "Get post detail V2(supports URL)",
          "link": "/model-api-reference/platform-apis/threads/web/post-detail-v2"
        },
        {
          "text": "Get user posts",
          "link": "/model-api-reference/platform-apis/threads/web/user-posts"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Get user info",
          "link": "/model-api-reference/platform-apis/threads/web/user-info"
        },
        {
          "text": "Get user info by ID",
          "link": "/model-api-reference/platform-apis/threads/web/user-info-by-id"
        },
        {
          "text": "Get user reposts",
          "link": "/model-api-reference/platform-apis/threads/web/user-reposts"
        }
      ]
    }
  ]
} as const
