// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "TikTok",
  "slug": "tiktok",
  "operationCount": 161,
  "groups": [
    {
      "key": "ads",
      "label": "Ads",
      "operations": [
        {
          "text": "Get ad interactive analysis",
          "link": "/model-api-reference/platform-apis/tiktok/ads/ad-interactive-analysis"
        },
        {
          "text": "Get ad keyframe analysis",
          "link": "/model-api-reference/platform-apis/tiktok/ads/ad-keyframe-analysis"
        },
        {
          "text": "Get ad percentile data",
          "link": "/model-api-reference/platform-apis/tiktok/ads/ad-percentile"
        },
        {
          "text": "Get query suggestions",
          "link": "/model-api-reference/platform-apis/tiktok/ads/query-suggestions"
        },
        {
          "text": "Get recommended ads",
          "link": "/model-api-reference/platform-apis/tiktok/ads/recommended-ads"
        },
        {
          "text": "Get search modules config",
          "link": "/model-api-reference/platform-apis/tiktok/ads/configure-safety"
        },
        {
          "text": "Get single ad detail",
          "link": "/model-api-reference/platform-apis/tiktok/ads/ads-detail"
        },
        {
          "text": "Get supported location list",
          "link": "/model-api-reference/platform-apis/tiktok/ads/location-list"
        },
        {
          "text": "Get top ads spotlight",
          "link": "/model-api-reference/platform-apis/tiktok/ads/top-ads-spotlight"
        },
        {
          "text": "Get trending hashtag detail",
          "link": "/model-api-reference/platform-apis/tiktok/ads/trends-hashtag-detail"
        },
        {
          "text": "Get trending hashtag list",
          "link": "/model-api-reference/platform-apis/tiktok/ads/trends-hashtag-list"
        },
        {
          "text": "Search ads",
          "link": "/model-api-reference/platform-apis/tiktok/ads/search-ads"
        }
      ]
    },
    {
      "key": "creator",
      "label": "Creator Analytics",
      "operations": [
        {
          "text": "Get Creator Account Health Status",
          "link": "/model-api-reference/platform-apis/tiktok/creator/account-health-status"
        },
        {
          "text": "Get Creator Account Info",
          "link": "/model-api-reference/platform-apis/tiktok/creator/creator-account-info"
        },
        {
          "text": "Get Creator Account Overview",
          "link": "/model-api-reference/platform-apis/tiktok/creator/account-insights-overview"
        },
        {
          "text": "Get Creator Account Violation Record List",
          "link": "/model-api-reference/platform-apis/tiktok/creator/account-violation-list"
        },
        {
          "text": "Get Creator Live Overview",
          "link": "/model-api-reference/platform-apis/tiktok/creator/live-analytics-summary"
        },
        {
          "text": "Get Creator Product List Analytics",
          "link": "/model-api-reference/platform-apis/tiktok/creator/product-analytics-list"
        },
        {
          "text": "Get Creator Video List Analytics",
          "link": "/model-api-reference/platform-apis/tiktok/creator/video-list-analytics"
        },
        {
          "text": "Get Creator Video Overview",
          "link": "/model-api-reference/platform-apis/tiktok/creator/video-analytics-summary"
        },
        {
          "text": "Get Product Related Videos",
          "link": "/model-api-reference/platform-apis/tiktok/creator/product-related-videos"
        },
        {
          "text": "Get Showcase Product List",
          "link": "/model-api-reference/platform-apis/tiktok/creator/showcase-product-list"
        },
        {
          "text": "Get Video Associated Product List",
          "link": "/model-api-reference/platform-apis/tiktok/creator/video-associated-product-list"
        },
        {
          "text": "Get Video Audience Analysis Data",
          "link": "/model-api-reference/platform-apis/tiktok/creator/video-audience-stats"
        },
        {
          "text": "Get Video Detailed Statistics",
          "link": "/model-api-reference/platform-apis/tiktok/creator/video-detailed-stats"
        },
        {
          "text": "Get Video-Product Association Statistics",
          "link": "/model-api-reference/platform-apis/tiktok/creator/video-to-product-stats"
        }
      ]
    },
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Creator Search Insights",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/creator-search-insights"
        },
        {
          "text": "Creator Search Insights Detail",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/creator-search-insights-detail"
        },
        {
          "text": "Creator Search Insights Trend",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/creator-search-insights-trend"
        },
        {
          "text": "Creator Search Insights Videos",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/creator-search-insights-videos"
        },
        {
          "text": "Generate TikTok share link, call TikTok APP, and jump to the specified keyword search result",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/open-app-to-keyword-search"
        },
        {
          "text": "Get available tags for live room homepage recommendation",
          "link": "/model-api-reference/platform-apis/tiktok/web/live-recommend-tabs"
        },
        {
          "text": "Get comprehensive search results of specified keywords",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/general-search-result"
        },
        {
          "text": "Get daily trending search words",
          "link": "/model-api-reference/platform-apis/tiktok/web/trending-searchwords"
        },
        {
          "text": "Get details of specified hashtag",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/hashtag-detail"
        },
        {
          "text": "Get explore video data",
          "link": "/model-api-reference/platform-apis/tiktok/web/explore-post"
        },
        {
          "text": "Get general search list",
          "link": "/model-api-reference/platform-apis/tiktok/web/general-search"
        },
        {
          "text": "Get hashtag search results of specified keywords",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/hashtag-search-result"
        },
        {
          "text": "Get home feed(recommend) video data",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/home-feed"
        },
        {
          "text": "Get live room homepage recommendation list",
          "link": "/model-api-reference/platform-apis/tiktok/web/live-recommend"
        },
        {
          "text": "Get live search results of specified keywords",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/live-search-result"
        },
        {
          "text": "Get location search results",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/location-search"
        },
        {
          "text": "Get music search results of specified keywords",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/music-search-result"
        },
        {
          "text": "Get search keyword suggestions V2 (Mobile)",
          "link": "/model-api-reference/platform-apis/tiktok/shop-web/search-word-suggestion-v2"
        },
        {
          "text": "Get user search results of specified keywords",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/user-search-result"
        },
        {
          "text": "Get video list of specified hashtag",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/hashtag-video-list"
        },
        {
          "text": "Get video search results of specified keywords",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/video-search-result"
        },
        {
          "text": "Home Feed",
          "link": "/model-api-reference/platform-apis/tiktok/web/home-feed"
        },
        {
          "text": "Search follower list",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/search-follower-list"
        },
        {
          "text": "Search following list",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/search-following-list"
        },
        {
          "text": "Search keyword suggest",
          "link": "/model-api-reference/platform-apis/tiktok/web/search-keyword-suggest"
        },
        {
          "text": "Search live",
          "link": "/model-api-reference/platform-apis/tiktok/web/search-live"
        },
        {
          "text": "Search photo",
          "link": "/model-api-reference/platform-apis/tiktok/web/search-photo"
        },
        {
          "text": "Search products list V1",
          "link": "/model-api-reference/platform-apis/tiktok/shop-web/search-products-list"
        },
        {
          "text": "Search products list V2 (Mobile)",
          "link": "/model-api-reference/platform-apis/tiktok/shop-web/search-products-list-v2"
        },
        {
          "text": "Search user",
          "link": "/model-api-reference/platform-apis/tiktok/web/search-user"
        },
        {
          "text": "Search video",
          "link": "/model-api-reference/platform-apis/tiktok/web/search-video"
        },
        {
          "text": "Similar User Recommendations",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/similar-user-recommendations"
        },
        {
          "text": "Tag Detail",
          "link": "/model-api-reference/platform-apis/tiktok/web/tag-detail"
        },
        {
          "text": "Tag Post",
          "link": "/model-api-reference/platform-apis/tiktok/web/tag-post"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Get comment keywords analysis",
          "link": "/model-api-reference/platform-apis/tiktok/analytics/comment-keywords"
        },
        {
          "text": "Get comment replies data of specified video",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/video-comment-replies"
        },
        {
          "text": "Get product reviews V1",
          "link": "/model-api-reference/platform-apis/tiktok/shop-web/product-reviews"
        },
        {
          "text": "Get product reviews V2",
          "link": "/model-api-reference/platform-apis/tiktok/shop-web/product-reviews-v2"
        },
        {
          "text": "Get single video comments data",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/video-comments"
        },
        {
          "text": "Get video comment replies",
          "link": "/model-api-reference/platform-apis/tiktok/web/post-comment-reply"
        },
        {
          "text": "Get video comments",
          "link": "/model-api-reference/platform-apis/tiktok/web/post-comment"
        }
      ]
    },
    {
      "key": "live",
      "label": "Live",
      "operations": [
        {
          "text": "Batch check if live rooms are online",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/check-live-room-online-batch"
        },
        {
          "text": "Batch live room start status check",
          "link": "/model-api-reference/platform-apis/tiktok/web/batch-check-live-alive"
        },
        {
          "text": "Check if live room is online",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/check-live-room-online"
        },
        {
          "text": "Extract live room ID from live room link",
          "link": "/model-api-reference/platform-apis/tiktok/web/live-room-id"
        },
        {
          "text": "Get data of specified live room",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/live-room-info"
        },
        {
          "text": "Get information of specified Webcast user",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/webcast-user-info"
        },
        {
          "text": "Get live daily rank data",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/live-daily-rank"
        },
        {
          "text": "Get live room gift list",
          "link": "/model-api-reference/platform-apis/tiktok/web/live-gift-list"
        },
        {
          "text": "Get live room information via live link",
          "link": "/model-api-reference/platform-apis/tiktok/web/live-data"
        },
        {
          "text": "Get live room product list data",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/live-room-product-list"
        },
        {
          "text": "Get live room product list data V2",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/live-room-product-list-v2"
        },
        {
          "text": "Get live room ranking list",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/live-ranking-list"
        },
        {
          "text": "Get user live details",
          "link": "/model-api-reference/platform-apis/tiktok/web/user-live-detail"
        },
        {
          "text": "Live room start status check",
          "link": "/model-api-reference/platform-apis/tiktok/web/check-live-alive"
        },
        {
          "text": "tiktok live room danmaku parameters",
          "link": "/model-api-reference/platform-apis/tiktok/web/live-im-fetch"
        }
      ]
    },
    {
      "key": "commerce",
      "label": "Commerce",
      "operations": [
        {
          "text": "Get hot selling products list",
          "link": "/model-api-reference/platform-apis/tiktok/shop-web/hot-selling-products-list"
        },
        {
          "text": "Get product category list",
          "link": "/model-api-reference/platform-apis/tiktok/shop-web/products-category-list"
        },
        {
          "text": "Get product detail V1(Full data)",
          "link": "/model-api-reference/platform-apis/tiktok/shop-web/product-detail"
        },
        {
          "text": "Get product detail V2 (Less Data)",
          "link": "/model-api-reference/platform-apis/tiktok/shop-web/product-detail-v2"
        },
        {
          "text": "Get product detail V3 (Full Data)",
          "link": "/model-api-reference/platform-apis/tiktok/shop-web/product-detail-v3"
        },
        {
          "text": "Get Product ID by Share Link",
          "link": "/model-api-reference/platform-apis/tiktok/shop-web/product-id-by-share-link"
        },
        {
          "text": "Get products by category ID",
          "link": "/model-api-reference/platform-apis/tiktok/shop-web/products-by-category-id"
        },
        {
          "text": "Get seller products list V1",
          "link": "/model-api-reference/platform-apis/tiktok/shop-web/seller-products-list"
        },
        {
          "text": "Get seller products list V2 (Mobile)",
          "link": "/model-api-reference/platform-apis/tiktok/shop-web/seller-products-list-v2"
        },
        {
          "text": "Get shop home page data",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/shop-home"
        },
        {
          "text": "Get shop home page list data",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/shop-home-page-list"
        },
        {
          "text": "Get Shop ID by Share Link",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/shop-id-by-share-link"
        },
        {
          "text": "Get Shop ID by Share Link",
          "link": "/model-api-reference/platform-apis/tiktok/shop-web/shop-id-by-share-link"
        },
        {
          "text": "Get shop information data",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/shop-info"
        }
      ]
    },
    {
      "key": "messaging",
      "label": "Messaging",
      "operations": [
        {
          "text": "Generate TikTok share link, call TikTok APP, and send private messages to specified users",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/open-app-to-send-private-message"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Batch Get Video Information",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/multi-video"
        },
        {
          "text": "Batch Get Video Information V2",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/multi-video-v2"
        },
        {
          "text": "Detect fake views in video",
          "link": "/model-api-reference/platform-apis/tiktok/analytics/detect-fake-views"
        },
        {
          "text": "Generate TikTok share link, call TikTok APP, and jump to the specified video details page",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/open-app-to-video-detail"
        },
        {
          "text": "Get details of specified music",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/music-detail"
        },
        {
          "text": "Get single video data",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/one-video"
        },
        {
          "text": "Get single video data",
          "link": "/model-api-reference/platform-apis/tiktok/web/post-detail"
        },
        {
          "text": "Get single video data by sharing link",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/one-video-by-share-url"
        },
        {
          "text": "Get single video data by sharing link",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/one-video-by-share-url-v2"
        },
        {
          "text": "Get single video data V2",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/one-video-v2"
        },
        {
          "text": "Get single video data V2",
          "link": "/model-api-reference/platform-apis/tiktok/web/post-detail-v2"
        },
        {
          "text": "Get single video data V3 (support country parameter)",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/one-video-v3"
        },
        {
          "text": "Get user homepage video data V1",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/user-post-videos"
        },
        {
          "text": "Get user homepage video data V2",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/user-post-videos-v2"
        },
        {
          "text": "Get user homepage video data V3 (simplified data - faster)",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/user-post-videos-v3"
        },
        {
          "text": "Get user like video data",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/user-like-videos"
        },
        {
          "text": "Get user music list data",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/user-music-list"
        },
        {
          "text": "Get user posts",
          "link": "/model-api-reference/platform-apis/tiktok/web/user-post"
        },
        {
          "text": "Get user repost video data",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/user-repost-videos"
        },
        {
          "text": "Get video list of specified music",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/music-video-list"
        },
        {
          "text": "Get video metrics",
          "link": "/model-api-reference/platform-apis/tiktok/analytics/video-metrics"
        },
        {
          "text": "Music Chart List",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/music-chart-list"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Extract list user sec_user_id",
          "link": "/model-api-reference/platform-apis/tiktok/web/all-sec-user-id"
        },
        {
          "text": "Extract user sec_user_id",
          "link": "/model-api-reference/platform-apis/tiktok/web/sec-user-id"
        },
        {
          "text": "Extract user user_id",
          "link": "/model-api-reference/platform-apis/tiktok/web/user-id"
        },
        {
          "text": "Generate TikTok share link, call TikTok APP, and jump to the specified user profile",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/open-app-to-user-profile"
        },
        {
          "text": "Get creator info and milestones",
          "link": "/model-api-reference/platform-apis/tiktok/analytics/creator-info-and-milestones"
        },
        {
          "text": "Get follower list of specified user",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/user-follower-list"
        },
        {
          "text": "Get following list of specified user",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/user-following-list"
        },
        {
          "text": "Get information of specified user",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/user-profile"
        },
        {
          "text": "Get user account country by username",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/user-country-by-username"
        },
        {
          "text": "Get user favorites",
          "link": "/model-api-reference/platform-apis/tiktok/web/user-collect"
        },
        {
          "text": "Get user followers",
          "link": "/model-api-reference/platform-apis/tiktok/web/user-fans"
        },
        {
          "text": "Get user followings",
          "link": "/model-api-reference/platform-apis/tiktok/web/user-follow"
        },
        {
          "text": "Get user likes",
          "link": "/model-api-reference/platform-apis/tiktok/web/user-like"
        },
        {
          "text": "Get user mix list",
          "link": "/model-api-reference/platform-apis/tiktok/web/user-mix"
        },
        {
          "text": "Get user play list",
          "link": "/model-api-reference/platform-apis/tiktok/web/user-play-list"
        },
        {
          "text": "Get user profile",
          "link": "/model-api-reference/platform-apis/tiktok/web/user-profile"
        },
        {
          "text": "Get user reposts",
          "link": "/model-api-reference/platform-apis/tiktok/web/user-repost"
        },
        {
          "text": "Get user_id and sec_user_id by Username",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/user-id-and-sec-user-id-by-username"
        }
      ]
    },
    {
      "key": "utilities",
      "label": "Utilities",
      "operations": [
        {
          "text": "Batch get gift names by gift IDs ($0.025/call, suggest 50)",
          "link": "/model-api-reference/platform-apis/tiktok/web/gift-names-by-ids"
        },
        {
          "text": "Decrypt strData",
          "link": "/model-api-reference/platform-apis/tiktok/web/decrypt-str-data"
        },
        {
          "text": "Encrypt strData",
          "link": "/model-api-reference/platform-apis/tiktok/web/encrypt-str-data"
        },
        {
          "text": "Extract list video id",
          "link": "/model-api-reference/platform-apis/tiktok/web/all-aweme-id"
        },
        {
          "text": "Extract single video id",
          "link": "/model-api-reference/platform-apis/tiktok/web/aweme-id"
        },
        {
          "text": "Generate browser fingerprint",
          "link": "/model-api-reference/platform-apis/tiktok/web/generate-fingerprint"
        },
        {
          "text": "Generate hashed ID",
          "link": "/model-api-reference/platform-apis/tiktok/web/generate-hashed-id"
        },
        {
          "text": "Generate real msToken",
          "link": "/model-api-reference/platform-apis/tiktok/web/generate-real-ms-token"
        },
        {
          "text": "Generate TikTok WSS X-Bogus signature",
          "link": "/model-api-reference/platform-apis/tiktok/web/generate-wss-xb-signature"
        },
        {
          "text": "Generate ttwid",
          "link": "/model-api-reference/platform-apis/tiktok/web/generate-ttwid"
        },
        {
          "text": "Generate web_id",
          "link": "/model-api-reference/platform-apis/tiktok/web/generate-webid"
        },
        {
          "text": "Generate X-Mssdk-Info",
          "link": "/model-api-reference/platform-apis/tiktok/web/generate-x-mssdk-info"
        },
        {
          "text": "Generate XBogus",
          "link": "/model-api-reference/platform-apis/tiktok/web/generate-xbogus"
        },
        {
          "text": "Generate XGnarly",
          "link": "/model-api-reference/platform-apis/tiktok/web/generate-xgnarly"
        },
        {
          "text": "Generate XGnarly and XBogus",
          "link": "/model-api-reference/platform-apis/tiktok/web/generate-xgnarly-and-xbogus"
        },
        {
          "text": "Get gift name by gift ID",
          "link": "/model-api-reference/platform-apis/tiktok/web/gift-name-by-id"
        },
        {
          "text": "Get list unique_id",
          "link": "/model-api-reference/platform-apis/tiktok/web/all-unique-id"
        },
        {
          "text": "Get share QR code",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/share-qr-code"
        },
        {
          "text": "Get the guest Cookie",
          "link": "/model-api-reference/platform-apis/tiktok/web/web-guest-cookie"
        },
        {
          "text": "Get user unique_id",
          "link": "/model-api-reference/platform-apis/tiktok/web/unique-id"
        },
        {
          "text": "Register device for TikTok Web",
          "link": "/model-api-reference/platform-apis/tiktok/web/device-register"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Get content translation data",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/content-translate"
        },
        {
          "text": "Get share short link",
          "link": "/model-api-reference/platform-apis/tiktok/app-v3/share-short-link"
        }
      ]
    }
  ]
} as const
