// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Toutiao",
  "slug": "toutiao",
  "operationCount": 7,
  "groups": [
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Get comments of specified post",
          "link": "/model-api-reference/platform-apis/toutiao/app/comments"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Get information of specified video",
          "link": "/model-api-reference/platform-apis/toutiao/app/video-info"
        },
        {
          "text": "Get information of specified video",
          "link": "/model-api-reference/platform-apis/toutiao/web/video-info"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Get information of specified user",
          "link": "/model-api-reference/platform-apis/toutiao/app/user-info"
        },
        {
          "text": "Get user_id from user profile",
          "link": "/model-api-reference/platform-apis/toutiao/app/user-id"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Get information of specified article",
          "link": "/model-api-reference/platform-apis/toutiao/app/article-info"
        },
        {
          "text": "Get information of specified article",
          "link": "/model-api-reference/platform-apis/toutiao/web/article-info"
        }
      ]
    }
  ]
} as const
