// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Twitter",
  "slug": "twitter",
  "operationCount": 12,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Search",
          "link": "/model-api-reference/platform-apis/twitter/web/search-timeline"
        },
        {
          "text": "Trending",
          "link": "/model-api-reference/platform-apis/twitter/web/trending"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Get comments",
          "link": "/model-api-reference/platform-apis/twitter/web/post-comments"
        },
        {
          "text": "Get the latest tweet comments",
          "link": "/model-api-reference/platform-apis/twitter/web/latest-post-comments"
        },
        {
          "text": "Get user tweet replies",
          "link": "/model-api-reference/platform-apis/twitter/web/user-tweet-replies"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Get user media",
          "link": "/model-api-reference/platform-apis/twitter/web/user-media"
        },
        {
          "text": "Get user post",
          "link": "/model-api-reference/platform-apis/twitter/web/user-post-tweet"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Get user profile",
          "link": "/model-api-reference/platform-apis/twitter/web/user-profile"
        },
        {
          "text": "ReTweet User list",
          "link": "/model-api-reference/platform-apis/twitter/web/retweet-user-list"
        },
        {
          "text": "User Followers",
          "link": "/model-api-reference/platform-apis/twitter/web/user-followers"
        },
        {
          "text": "User Followings",
          "link": "/model-api-reference/platform-apis/twitter/web/user-followings"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Get single tweet data",
          "link": "/model-api-reference/platform-apis/twitter/web/tweet-detail"
        }
      ]
    }
  ]
} as const
