// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "WeChat Search",
  "slug": "wechat-search",
  "operationCount": 2,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "WeChat Channels Video Search",
          "link": "/model-api-reference/platform-apis/wechat-search/v2/search-videos"
        },
        {
          "text": "WeChat Universal Search",
          "link": "/model-api-reference/platform-apis/wechat-search/v2/search"
        }
      ]
    }
  ]
} as const
