// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "WeChat MP",
  "slug": "wechat-mp",
  "operationCount": 9,
  "groups": [
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Get WeChat MP Article Comments",
          "link": "/model-api-reference/platform-apis/wechat-mp/v2/article-comments"
        },
        {
          "text": "Get WeChat MP Comment Replies",
          "link": "/model-api-reference/platform-apis/wechat-mp/v2/comment-replies"
        }
      ]
    },
    {
      "key": "messaging",
      "label": "Messaging",
      "operations": [
        {
          "text": "Get WeChat MP Article Ads",
          "link": "/model-api-reference/platform-apis/wechat-mp/v2/article-ad"
        },
        {
          "text": "Get WeChat MP Article Detail",
          "link": "/model-api-reference/platform-apis/wechat-mp/v2/article-detail"
        },
        {
          "text": "Get WeChat MP Article Stats",
          "link": "/model-api-reference/platform-apis/wechat-mp/v2/article-stats"
        },
        {
          "text": "Get WeChat MP Related Articles",
          "link": "/model-api-reference/platform-apis/wechat-mp/v2/related-articles"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Get WeChat MP Account Articles",
          "link": "/model-api-reference/platform-apis/wechat-mp/v2/account-articles"
        },
        {
          "text": "Get WeChat MP Account Profile",
          "link": "/model-api-reference/platform-apis/wechat-mp/v2/account-profile"
        },
        {
          "text": "Get WeChat MP Account Services & Custom Menu",
          "link": "/model-api-reference/platform-apis/wechat-mp/v2/account-services"
        }
      ]
    }
  ]
} as const
