// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "WeChat Channels",
  "slug": "wechat-channels",
  "operationCount": 12,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Search Videos Within a WeChat Channel",
          "link": "/model-api-reference/platform-apis/wechat-channels/v2/search-channel-videos"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Get WeChat Channels Video Comments",
          "link": "/model-api-reference/platform-apis/wechat-channels/v2/video-comments"
        }
      ]
    },
    {
      "key": "live",
      "label": "Live",
      "operations": [
        {
          "text": "Get WeChat Channels Live Detail",
          "link": "/model-api-reference/platform-apis/wechat-channels/v2/live-detail"
        },
        {
          "text": "Get WeChat Channels Live History",
          "link": "/model-api-reference/platform-apis/wechat-channels/v2/live-history"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Generate WeChat Channels Video Share URL",
          "link": "/model-api-reference/platform-apis/wechat-channels/v2/video-share-url"
        },
        {
          "text": "Get WeChat Channels Collection Videos",
          "link": "/model-api-reference/platform-apis/wechat-channels/v2/collection-videos"
        },
        {
          "text": "Get WeChat Channels User Videos",
          "link": "/model-api-reference/platform-apis/wechat-channels/v2/user-videos"
        },
        {
          "text": "Get WeChat Channels Video Detail",
          "link": "/model-api-reference/platform-apis/wechat-channels/v2/video-detail"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Convert Channel ID to Finder Username",
          "link": "/model-api-reference/platform-apis/wechat-channels/v2/channel-id-to-username"
        },
        {
          "text": "Get WeChat Channels Account Info",
          "link": "/model-api-reference/platform-apis/wechat-channels/v2/channel-info"
        },
        {
          "text": "Get WeChat Channels User Collections",
          "link": "/model-api-reference/platform-apis/wechat-channels/v2/user-collections"
        },
        {
          "text": "Get WeChat Channels User Profile & Stats",
          "link": "/model-api-reference/platform-apis/wechat-channels/v2/user-profile"
        }
      ]
    }
  ]
} as const
