// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Weibo",
  "slug": "weibo",
  "operationCount": 64,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "AI Smart Search",
          "link": "/model-api-reference/platform-apis/weibo/app/ai-smart-search"
        },
        {
          "text": "Comprehensive search",
          "link": "/model-api-reference/platform-apis/weibo/app/search-all"
        },
        {
          "text": "Get channel feed by name",
          "link": "/model-api-reference/platform-apis/weibo/web/channel-feed"
        },
        {
          "text": "Get channel trend top",
          "link": "/model-api-reference/platform-apis/weibo/web/trend-top"
        },
        {
          "text": "Get home recommend feed",
          "link": "/model-api-reference/platform-apis/weibo/app/home-recommend-feed"
        },
        {
          "text": "Get hot search",
          "link": "/model-api-reference/platform-apis/weibo/app/hot-search"
        },
        {
          "text": "Get hot search categories",
          "link": "/model-api-reference/platform-apis/weibo/app/hot-search-categories"
        },
        {
          "text": "Get hot search ranking",
          "link": "/model-api-reference/platform-apis/weibo/web/hot-search"
        },
        {
          "text": "Get search page hot topics",
          "link": "/model-api-reference/platform-apis/weibo/web/search-topics"
        },
        {
          "text": "Get user profile feed",
          "link": "/model-api-reference/platform-apis/weibo/app/user-profile-feed"
        },
        {
          "text": "Get user recommend timeline",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/user-recommend-timeline"
        },
        {
          "text": "Get video featured feed",
          "link": "/model-api-reference/platform-apis/weibo/app/video-featured-feed"
        },
        {
          "text": "Get Weibo complete hot search ranking (50 items)",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/hot-search-summary"
        },
        {
          "text": "Get Weibo hot search index (10 items)",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/hot-search-index"
        },
        {
          "text": "Get Weibo hot search ranking",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/hot-search"
        },
        {
          "text": "Get Weibo similar search recommendations",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/similar-search"
        },
        {
          "text": "Search user posts",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/search-user-posts"
        },
        {
          "text": "Search Weibo",
          "link": "/model-api-reference/platform-apis/weibo/web/search"
        },
        {
          "text": "User search",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/user-search"
        },
        {
          "text": "Weibo Advanced Search",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/advanced-search"
        },
        {
          "text": "Weibo AI Search",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/ai-search"
        },
        {
          "text": "Weibo AI Search Content Extension",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/ai-related-search"
        },
        {
          "text": "Weibo picture search",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/pic-search"
        },
        {
          "text": "Weibo Realtime Search",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/realtime-search"
        },
        {
          "text": "Weibo topic search",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/topic-search"
        },
        {
          "text": "Weibo video search (hot/all)",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/video-search"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Check if Weibo allows image comments",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/check-allow-comment-with-pic"
        },
        {
          "text": "Get comment replies",
          "link": "/model-api-reference/platform-apis/weibo/web/comment-replies"
        },
        {
          "text": "Get post comments",
          "link": "/model-api-reference/platform-apis/weibo/app/status-comments"
        },
        {
          "text": "Get post comments",
          "link": "/model-api-reference/platform-apis/weibo/web/post-comments"
        },
        {
          "text": "Get Weibo comments",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/post-comments"
        },
        {
          "text": "Get Weibo sub-comments",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/post-sub-comments"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Get post detail",
          "link": "/model-api-reference/platform-apis/weibo/web/post-detail"
        },
        {
          "text": "Get single post data",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/post-detail"
        },
        {
          "text": "Get user all videos",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/user-video-list"
        },
        {
          "text": "Get user posts",
          "link": "/model-api-reference/platform-apis/weibo/web/user-posts"
        },
        {
          "text": "Get user video collection detail",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/user-video-collection-detail"
        },
        {
          "text": "Get user video collection list",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/user-video-collection-list"
        },
        {
          "text": "Get user videos",
          "link": "/model-api-reference/platform-apis/weibo/app/user-videos"
        },
        {
          "text": "Get video detail",
          "link": "/model-api-reference/platform-apis/weibo/app/video-detail"
        },
        {
          "text": "Get Weibo user original posts",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/user-original-posts"
        },
        {
          "text": "Get Weibo user posts",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/user-posts"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Get channel config list",
          "link": "/model-api-reference/platform-apis/weibo/web/config-list"
        },
        {
          "text": "Get user album",
          "link": "/model-api-reference/platform-apis/weibo/app/user-album"
        },
        {
          "text": "Get user articles",
          "link": "/model-api-reference/platform-apis/weibo/app/user-articles"
        },
        {
          "text": "Get user audios",
          "link": "/model-api-reference/platform-apis/weibo/app/user-audios"
        },
        {
          "text": "Get user basic information",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/user-basic-info"
        },
        {
          "text": "Get user detail information",
          "link": "/model-api-reference/platform-apis/weibo/app/user-info-detail"
        },
        {
          "text": "Get user fans list",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/user-fans"
        },
        {
          "text": "Get user following list",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/user-following"
        },
        {
          "text": "Get user information",
          "link": "/model-api-reference/platform-apis/weibo/app/user-info"
        },
        {
          "text": "Get user information",
          "link": "/model-api-reference/platform-apis/weibo/web/user-info"
        },
        {
          "text": "Get user information",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/user-info"
        },
        {
          "text": "Get user super topics",
          "link": "/model-api-reference/platform-apis/weibo/app/user-super-topics"
        },
        {
          "text": "Get user timeline",
          "link": "/model-api-reference/platform-apis/weibo/app/user-timeline"
        }
      ]
    },
    {
      "key": "utilities",
      "label": "Utilities",
      "operations": [
        {
          "text": "Get post detail",
          "link": "/model-api-reference/platform-apis/weibo/app/status-detail"
        },
        {
          "text": "Get post likes",
          "link": "/model-api-reference/platform-apis/weibo/app/status-likes"
        },
        {
          "text": "Get post reposts",
          "link": "/model-api-reference/platform-apis/weibo/app/status-reposts"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Get all groups information",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/all-groups"
        },
        {
          "text": "Get hot ranking timeline",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/hot-ranking-timeline"
        },
        {
          "text": "Get Weibo entertainment ranking",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/entertainment-ranking"
        },
        {
          "text": "Get Weibo life ranking",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/life-ranking"
        },
        {
          "text": "Get Weibo social ranking",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/social-ranking"
        },
        {
          "text": "Region City List",
          "link": "/model-api-reference/platform-apis/weibo/web-v2/city-list"
        }
      ]
    }
  ]
} as const
