// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Xiaohongshu",
  "slug": "xiaohongshu",
  "operationCount": 36,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Fetch homepage feed",
          "link": "/model-api-reference/platform-apis/xiaohongshu/web-v3/homefeed"
        },
        {
          "text": "Fetch search suggestions",
          "link": "/model-api-reference/platform-apis/xiaohongshu/web-v3/search-suggest"
        },
        {
          "text": "Get creator hot inspiration feed",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/creator-hot-inspiration-feed"
        },
        {
          "text": "Get creator inspiration feed",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/creator-inspiration-feed"
        },
        {
          "text": "Get topic feed",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/topic-feed"
        },
        {
          "text": "Search groups",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/search-groups"
        },
        {
          "text": "Search images",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/search-images"
        },
        {
          "text": "Search notes",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/search-notes"
        },
        {
          "text": "Search products",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/search-products"
        },
        {
          "text": "Search users",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/search-users"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Get note comments",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/note-comments"
        },
        {
          "text": "Get note sub comments",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/note-sub-comments"
        },
        {
          "text": "Get product review overview",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/product-review-overview"
        },
        {
          "text": "Get product reviews",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/product-reviews"
        }
      ]
    },
    {
      "key": "commerce",
      "label": "Commerce",
      "operations": [
        {
          "text": "Get product detail",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/product-detail"
        },
        {
          "text": "Get product recommendations",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/product-recommendations"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Get video note detail",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/video-note-detail"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Fetch user info",
          "link": "/model-api-reference/platform-apis/xiaohongshu/web-v3/user-info"
        },
        {
          "text": "Get PGY blogger fans history",
          "link": "/model-api-reference/platform-apis/xiaohongshu/pgy/blogger-fans-history"
        },
        {
          "text": "Get PGY blogger fans profile",
          "link": "/model-api-reference/platform-apis/xiaohongshu/pgy/blogger-fans-profile"
        },
        {
          "text": "Get PGY blogger fans summary",
          "link": "/model-api-reference/platform-apis/xiaohongshu/pgy/blogger-fans-summary"
        },
        {
          "text": "Get user faved notes",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/user-faved-notes"
        },
        {
          "text": "Get user info",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/user-info"
        },
        {
          "text": "Get user posted notes",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/user-posted-notes"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Fetch homepage categories",
          "link": "/model-api-reference/platform-apis/xiaohongshu/web-v3/homefeed-categories"
        },
        {
          "text": "Fetch note detail",
          "link": "/model-api-reference/platform-apis/xiaohongshu/web-v3/note-detail"
        },
        {
          "text": "Fetch Xiaohongshu hot list",
          "link": "/model-api-reference/platform-apis/xiaohongshu/web-v3/hot-list"
        },
        {
          "text": "Get image note detail",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/image-note-detail"
        },
        {
          "text": "Get PGY blogger core data",
          "link": "/model-api-reference/platform-apis/xiaohongshu/pgy/blogger-core-data"
        },
        {
          "text": "Get PGY blogger data summary",
          "link": "/model-api-reference/platform-apis/xiaohongshu/pgy/blogger-data-summary"
        },
        {
          "text": "Get PGY blogger detail",
          "link": "/model-api-reference/platform-apis/xiaohongshu/pgy/blogger-detail"
        },
        {
          "text": "Get PGY blogger list",
          "link": "/model-api-reference/platform-apis/xiaohongshu/pgy/blogger-list"
        },
        {
          "text": "Get PGY blogger notes",
          "link": "/model-api-reference/platform-apis/xiaohongshu/pgy/blogger-notes"
        },
        {
          "text": "Get PGY blogger notes rate",
          "link": "/model-api-reference/platform-apis/xiaohongshu/pgy/blogger-notes-rate"
        },
        {
          "text": "Get PGY note detail",
          "link": "/model-api-reference/platform-apis/xiaohongshu/pgy/note-detail"
        },
        {
          "text": "Get topic info",
          "link": "/model-api-reference/platform-apis/xiaohongshu/app-v2/topic-info"
        }
      ]
    }
  ]
} as const
