// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Xigua",
  "slug": "xigua",
  "operationCount": 7,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Search video",
          "link": "/model-api-reference/platform-apis/xigua/app-v2/search-video"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Video comment list",
          "link": "/model-api-reference/platform-apis/xigua/app-v2/video-comment-list"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Get single video data",
          "link": "/model-api-reference/platform-apis/xigua/app-v2/one-video"
        },
        {
          "text": "Get single video data V2",
          "link": "/model-api-reference/platform-apis/xigua/app-v2/one-video-v2"
        },
        {
          "text": "Get single video play URL",
          "link": "/model-api-reference/platform-apis/xigua/app-v2/one-video-play-url"
        },
        {
          "text": "Get user post list",
          "link": "/model-api-reference/platform-apis/xigua/app-v2/user-post-list"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Personal information",
          "link": "/model-api-reference/platform-apis/xigua/app-v2/user-info"
        }
      ]
    }
  ]
} as const
