// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "YouTube",
  "slug": "youtube",
  "operationCount": 38,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "General search (raw data, recommend V2)",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/general-search"
        },
        {
          "text": "General search V2",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/general-search-v2"
        },
        {
          "text": "Get related videos",
          "link": "/model-api-reference/platform-apis/youtube/web/relate-video"
        },
        {
          "text": "Get related videos",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/related-videos"
        },
        {
          "text": "Get search suggestions",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/search-suggestions"
        },
        {
          "text": "Get trending videos",
          "link": "/model-api-reference/platform-apis/youtube/web/trending-videos"
        },
        {
          "text": "Search channel",
          "link": "/model-api-reference/platform-apis/youtube/web/search-channel"
        },
        {
          "text": "Search channels",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/search-channels"
        },
        {
          "text": "Search video",
          "link": "/model-api-reference/platform-apis/youtube/web/search-video"
        },
        {
          "text": "Shorts search (raw data, recommend V2)",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/shorts-search"
        },
        {
          "text": "Shorts search V2",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/shorts-search-v2"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Community",
      "operations": [
        {
          "text": "Get channel community posts",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/channel-community-posts"
        },
        {
          "text": "Get post comment replies",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/post-comment-replies"
        },
        {
          "text": "Get post comments",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/post-comments"
        },
        {
          "text": "Get video comments",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/video-comments"
        },
        {
          "text": "Get video sub comments",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/video-comment-replies"
        }
      ]
    },
    {
      "key": "videos",
      "label": "Videos & Media",
      "operations": [
        {
          "text": "Get channel short videos",
          "link": "/model-api-reference/platform-apis/youtube/web/channel-short-videos"
        },
        {
          "text": "Get channel shorts",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/channel-shorts"
        },
        {
          "text": "Get channel videos",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/channel-videos"
        },
        {
          "text": "Get channel videos V2",
          "link": "/model-api-reference/platform-apis/youtube/web/channel-videos-v2"
        },
        {
          "text": "Get post detail",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/post-detail"
        },
        {
          "text": "Get signed video stream URL",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/signed-stream-url"
        },
        {
          "text": "Get video captions",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/video-captions"
        },
        {
          "text": "Get video captions async job result",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/video-captions-result"
        },
        {
          "text": "Get video information",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/video-info"
        },
        {
          "text": "Get video information V1",
          "link": "/model-api-reference/platform-apis/youtube/web/video-info"
        },
        {
          "text": "Get video information V2",
          "link": "/model-api-reference/platform-apis/youtube/web/video-info-v2"
        },
        {
          "text": "Get video information V2",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/video-info-v2"
        },
        {
          "text": "Get video streams info",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/video-streams"
        },
        {
          "text": "Get video streams info V2",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/video-streams-v2"
        },
        {
          "text": "Get video subtitles",
          "link": "/model-api-reference/platform-apis/youtube/web/video-subtitles"
        }
      ]
    },
    {
      "key": "channels",
      "label": "Channels & Users",
      "operations": [
        {
          "text": "Get channel description",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/channel-description"
        },
        {
          "text": "Get channel ID",
          "link": "/model-api-reference/platform-apis/youtube/web/channel-id"
        },
        {
          "text": "Get channel ID from URL",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/channel-id"
        },
        {
          "text": "Get channel ID from URL V2",
          "link": "/model-api-reference/platform-apis/youtube/web/channel-id-v2"
        },
        {
          "text": "Get channel information",
          "link": "/model-api-reference/platform-apis/youtube/web/channel-info"
        },
        {
          "text": "Get channel URL from channel ID",
          "link": "/model-api-reference/platform-apis/youtube/web/channel-url"
        },
        {
          "text": "Get channel URL from channel ID",
          "link": "/model-api-reference/platform-apis/youtube/web-v2/channel-url"
        }
      ]
    }
  ]
} as const
