// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
export default {
  "platform": "Zhihu",
  "slug": "zhihu",
  "operationCount": 41,
  "groups": [
    {
      "key": "search",
      "label": "Search & Discovery",
      "operations": [
        {
          "text": "Get Zhihu AI Search (v2)",
          "link": "/model-api-reference/platform-apis/zhihu/web/ai-search-stream"
        },
        {
          "text": "Get Zhihu Article Search V3",
          "link": "/model-api-reference/platform-apis/zhihu/web/article-search-v3"
        },
        {
          "text": "Get Zhihu Column Search V3",
          "link": "/model-api-reference/platform-apis/zhihu/web/column-search-v3"
        },
        {
          "text": "Get Zhihu Ebook Search V3",
          "link": "/model-api-reference/platform-apis/zhihu/web/ebook-search-v3"
        },
        {
          "text": "Get Zhihu Hot Recommend",
          "link": "/model-api-reference/platform-apis/zhihu/web/hot-recommend"
        },
        {
          "text": "Get Zhihu Preset Search",
          "link": "/model-api-reference/platform-apis/zhihu/web/preset-search"
        },
        {
          "text": "Get Zhihu Recommend Followees",
          "link": "/model-api-reference/platform-apis/zhihu/web/recommend-followees"
        },
        {
          "text": "Get Zhihu Salt Search V3",
          "link": "/model-api-reference/platform-apis/zhihu/web/salt-search-v3"
        },
        {
          "text": "Get Zhihu Scholar Search V3",
          "link": "/model-api-reference/platform-apis/zhihu/web/scholar-search-v3"
        },
        {
          "text": "Get Zhihu Search Recommend",
          "link": "/model-api-reference/platform-apis/zhihu/web/search-recommend"
        },
        {
          "text": "Get Zhihu Search Suggest",
          "link": "/model-api-reference/platform-apis/zhihu/web/search-suggest"
        },
        {
          "text": "Get Zhihu Similar Column Recommend",
          "link": "/model-api-reference/platform-apis/zhihu/web/column-recommend"
        },
        {
          "text": "Get Zhihu Topic Search V3",
          "link": "/model-api-reference/platform-apis/zhihu/web/topic-search-v3"
        },
        {
          "text": "Get Zhihu User Search V3",
          "link": "/model-api-reference/platform-apis/zhihu/web/user-search-v3"
        },
        {
          "text": "Get Zhihu Video Search V3",
          "link": "/model-api-reference/platform-apis/zhihu/web/video-search-v3"
        }
      ]
    },
    {
      "key": "comments",
      "label": "Comments & Engagement",
      "operations": [
        {
          "text": "Get Zhihu Column Comment Config",
          "link": "/model-api-reference/platform-apis/zhihu/web/column-comment-config"
        },
        {
          "text": "Get Zhihu Comment V5",
          "link": "/model-api-reference/platform-apis/zhihu/web/comment-v5"
        },
        {
          "text": "Get Zhihu Pin Comments",
          "link": "/model-api-reference/platform-apis/zhihu/web/pin-comments"
        },
        {
          "text": "Get Zhihu Sub Comment V5",
          "link": "/model-api-reference/platform-apis/zhihu/web/sub-comment-v5"
        }
      ]
    },
    {
      "key": "content",
      "label": "Content & Video",
      "operations": [
        {
          "text": "Get Zhihu Video List",
          "link": "/model-api-reference/platform-apis/zhihu/web/video-list"
        }
      ]
    },
    {
      "key": "users",
      "label": "Users & Accounts",
      "operations": [
        {
          "text": "Get Zhihu User Answers",
          "link": "/model-api-reference/platform-apis/zhihu/web/user-answers"
        },
        {
          "text": "Get Zhihu User Articles",
          "link": "/model-api-reference/platform-apis/zhihu/web/user-articles"
        },
        {
          "text": "Get Zhihu User Columns",
          "link": "/model-api-reference/platform-apis/zhihu/web/user-follow-columns"
        },
        {
          "text": "Get Zhihu User Created Collections",
          "link": "/model-api-reference/platform-apis/zhihu/web/user-collections"
        },
        {
          "text": "Get Zhihu User Follow Collections",
          "link": "/model-api-reference/platform-apis/zhihu/web/user-follow-collections"
        },
        {
          "text": "Get Zhihu User Follow Questions",
          "link": "/model-api-reference/platform-apis/zhihu/web/user-follow-questions"
        },
        {
          "text": "Get Zhihu User Follow Topics",
          "link": "/model-api-reference/platform-apis/zhihu/web/user-follow-topics"
        },
        {
          "text": "Get Zhihu User Followers",
          "link": "/model-api-reference/platform-apis/zhihu/web/user-followers"
        },
        {
          "text": "Get Zhihu User Following",
          "link": "/model-api-reference/platform-apis/zhihu/web/user-followees"
        },
        {
          "text": "Get Zhihu User Included Articles",
          "link": "/model-api-reference/platform-apis/zhihu/web/user-included-articles"
        },
        {
          "text": "Get Zhihu User Info",
          "link": "/model-api-reference/platform-apis/zhihu/web/user-info"
        },
        {
          "text": "Get Zhihu User Pins",
          "link": "/model-api-reference/platform-apis/zhihu/web/user-pins"
        },
        {
          "text": "Get Zhihu User Segments",
          "link": "/model-api-reference/platform-apis/zhihu/web/user-segments"
        }
      ]
    },
    {
      "key": "other",
      "label": "Other",
      "operations": [
        {
          "text": "Get Zhihu Answer Detail",
          "link": "/model-api-reference/platform-apis/zhihu/web/answer-detail"
        },
        {
          "text": "Get Zhihu Column Article Detail",
          "link": "/model-api-reference/platform-apis/zhihu/web/column-article-detail"
        },
        {
          "text": "Get Zhihu Column Article Relationship",
          "link": "/model-api-reference/platform-apis/zhihu/web/column-relationship"
        },
        {
          "text": "Get Zhihu Column Articles",
          "link": "/model-api-reference/platform-apis/zhihu/web/column-articles"
        },
        {
          "text": "Get Zhihu Hot List",
          "link": "/model-api-reference/platform-apis/zhihu/web/hot-list"
        },
        {
          "text": "Get Zhihu Pin Detail",
          "link": "/model-api-reference/platform-apis/zhihu/web/pin-detail"
        },
        {
          "text": "Get Zhihu Question Answers",
          "link": "/model-api-reference/platform-apis/zhihu/web/question-answers"
        },
        {
          "text": "Get Zhihu Question Detail",
          "link": "/model-api-reference/platform-apis/zhihu/web/question-detail"
        }
      ]
    }
  ]
} as const
