// Generated by scripts/generate-llm-model-api-reference.mjs. Do not edit by hand.
// Model API Reference pages carry their own apiReferenceJson frontmatter,
// so this compatibility export intentionally stays empty.
export const modelApiReferenceSpecs: Record<string, unknown> = {}
